### ISSUE TITLE
Tooltip for blocks no longer shoes code in v1

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#1148]
In v0, when hovering over a block we get to see the code it represents

![image](https://user-images.githubusercontent.com/147113/44805478-3ec37b80-abbc-11e8-897a-e0da6db5ff5d.png)

(including loops containing their child blocks)

This is a valuable teaching tool and helps smooth the transition to JavaScript.

Is it an omission or deliberate decision that it's missing in v1?

**Comment by FranklinWhale** [comment]
I hope that this feature will return to v1 because it is really useful for the transition from block based coding to traditional coding.

Always showing the JavaScript code in tooltips may cause confusion for those who don't know JavaScript, but I think this issue can be solved by making the feature an opt-in. There may be a button under each tooltip so that, when the button is clicked by the user, the JavaScript representation of the block and its descendants is displayed under the button or in a popup dialog, which may further be copied by the user to the clipboard, further enhancing the C&P proposal in #1149.

Regarding syntax highlighting, I think it can be supported by using a syntax highlighter written in JavaScript, such as [highlight.js](https://github.com/highlightjs/highlight.js) and [Prism](https://github.com/PrismJS/prism), with custom styling to match the colors used by Monaco.

**Comment by FranklinWhale** [comment]
This feature was removed in Microsoft/pxt#3146 but can be re-enabled easily by reverting that commit in local copy.

@guillaumejenkins: Do you have any idea when the team will discuss this issue and probably also the C&P proposal?

**Comment by riknoll** [comment]
@FranklinWhale thanks for taking the time to investigate but we are a small team and we don't usually give timelines on individual issues

**Comment by FranklinWhale** [comment]
@riknoll I understand that :) The reason for asking for a possible timeline is that I am considering whether I should implement the proposal and submit a PR later. I would like to know more about the issue before working on that. Unfortunately, I am unable to find out any design note or discussion log related to the decision to remove...

**Comment by jaustin** [comment]
Discussed today and one proposed solution from @Jaqster was to have a 'show code' option in the right click menu, which takes the user to the code that this block is responsible for in the JavaScript view... 

Ideally, it'd be great if we can highlight that line in Monaco as we arrive in the JS view, and somehow signal to the user a simple way 'back' to blocks.

**Comment by abchatra** [comment]
Won't fix.
