### ISSUE TITLE
Add rounded hats to event handlers in v1

### ISSUE THREAD

**Issue by halspeed** [microsoft/pxt-microbit#1152]
Add rounded hats to event handlers in v1 to:

1. Provide a visual cue to make it more intuitive for users to understand which blocks can initiate code and reduce attempts to place blocks on top of event handlers, and
2. Be more consistent programming micro:bit across other block-based programming editors

Illustration of current flat-top event handler and proposed round-hat event handler:

![image](https://user-images.githubusercontent.com/29285304/44867270-fc964a80-ac4c-11e8-951d-83cc5756944b.png)

For functions consider making the hat across the entire top as illustrated below:

![image](https://user-images.githubusercontent.com/29285304/44866941-2a2ec400-ac4c-11e8-8323-f54ea1d9de14.png)

This could also be beneficial for users of other MakeCode targets.

References: 
https://github.com/Microsoft/pxt/issues/849
https://developers.google.com/blockly/guides/create-custom-blocks/block-paradigms#event_driven_program

**Comment by microbit-giles** [comment]
From my experience teaching block coding in K-12 over several years, I think rounded hats on event blocks would help facilitate children's learning.
- Some children are immediately comfortable with the idea of multiple event-handlers, but many are not. Having the round hat on the top of an event-handler is very useful for them: the teacher instructs them or they discover they need to add a second event-handler and they cannot figure out where it goes - 'it doesn't fit!' The 'not fitting' is important because it naturally leads them to the conclusion that it must stand alone.
- Our blocks are becoming more Scratch-like in other ways, e.g. hexagonal shapes, and this means children will find it easier to pick up MakeCode if another important part of the visual grammar is consistent.

**Comment by CleoQc** [comment]
I concur. Rounded hats make it clear that the blocks have to be at the top of a sequence.

**Comment by Jaqster** [comment]
This summer we ran a study with 14 students aged 9-18 (7 male, 7 female).  Study was set up as an AB trial followed by interviews.  
Almost all students:
a) understood the functionality of the blocks with and without the "hats" so there was no noticeable difference in understanding
b) from an aesthetic perspective, all students preferred the blocks without the "hats" citing that it had a more "modern" look, it was "simpler", the "rounded tops didn't fit with the feel of the rest of the blocks", or it reminded them of Scratch which was a product "for littler kids"

I'm happy to run a more comprehensive student survey in the next couple months to validate these preliminary results, but I don't want to make a big UI change without real user data to back up our design decisions.
