### ISSUE TITLE
Image matrix should be light purple - v1

### ISSUE THREAD

**Issue by halspeed** [Microsoft/pxt-microbit#1317]
**Describe the bug**
Under the Image menu, Create Image, Create Big Image and Icon Image have light blue LED matrix instead of having light purple LED matrix. This issue is most noticeable when the Icon Image dropdown is selected.

**Expected behavior**
Under the Basic menu, Show LEDs and Show Icon have light blue matrix to match the color of the blue block. I expect the Image blocks to have light purple matrix instead of light blue. This was the case in the Create Image block in v0.
 
**Screenshots**
![image](https://user-images.githubusercontent.com/29285304/46262596-f2c06b00-c4c8-11e8-9f3e-6a873fabd27a.png)

**Comment by abchatra** [comment]
This is probably intentional change for better contrast ration.  @samelhusseini can you provide your thoughts?

**Comment by halspeed** [comment]
For the Icon Image, the light blue is too bright against the purple, so it makes the white LEDs hard to see. Could another set of png images be created with light purple instead of light blue?

I don't know if this will be a problem if we lighten the block fill colors. FYI, Scratch 3.0 uses a darker matrix: 
![image](https://user-images.githubusercontent.com/29285304/46297070-6c0b9c80-c561-11e8-87a7-99f06dbac616.png)

**Comment by samelhusseini** [comment]
We reuse images between the two categories, ie: the images are pre-baked PNGs and not dynamically rendered, which means if we want to differentiate between the images shown under the basic (blue) category and the images shown under the images (purple) category, we would have to duplicate and download two sets of images which would increase the size of the editor (download size).

Since these blocks are less used, I would say this isn't worth the cost for bandwidth.

**Comment by samelhusseini** [comment]
Here's what that looks like: 
![screen shot 2018-10-01 at 10 07 34 am](https://user-images.githubusercontent.com/16690124/46303852-df151300-c561-11e8-994a-146d72050ab2.png)

**Comment by samelhusseini** [comment]
Thsi fix is also in beta: https://makecode.microbit.org/beta

**Comment by daniel-pers** [comment]
In beta version V1, the On color is still white instead of red. 
Is a fix planned ?

**Comment by pelikhan** [comment]
Screenshot?

**Comment by daniel-pers** [comment]
![capture 061018](https://user-images.githubusercontent.com/18614830/46573837-d9bd2b80-c99a-11e8-9b29-b2d4af4b9f45.JPG)

**Comment by halspeed** [comment]
The show icon and icon image dropdowns appear to each have a different lighter color for OFF LEDs, should those also be changed?

**Comment by pelikhan** [comment]
@daniel-pers could circle around what to look for?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by daniel-pers** [comment]
I think it's clear.
When a LED is On it should be red, but it's white (you have to look at each block).

**Comment by pelikhan** [comment]
This is by design - discussion here: https://github.com/Microsoft/pxt-microbit/issues/1349

**Comment by daniel-pers** [comment]
Thank you for this information. 
Personally I regret this choice of colors because it will complicate the task for some students.
On a real BBC micro:bit board we have these colors:
LED ON: white (or  light yellow, but certainly not blue or black)
LED OFF: red (not white as when off)
Wanting to avoid an optical problem (that I did not see) we create a problem even more embarrassing for childrens I think.
White or red pixels would be preferable to blue or white pixels.
It is a shame that design takes precedence over pedagogical effectiveness.

**Comment by samelhusseini** [comment]
RE: show icon having a different colour. I can't remember who mentioned to use a transparency fill on the images for the OFF colour, but I've tried that and it fixes the inconsistency issue between icons under the basic category vs icons in the images category.

Here are the two options for the OFF colour (light vs dark). The aim here is to make the icon fill (ON) pop out and the overall shape should be readable.

Light: 

![screen shot 2018-10-08 at 9 54 35 am](https://user-images.githubusercontent.com/16690124/46622762-7fc67e00-cae0-11e8-9e1a-17ae07db1a40.png)

Dark: (and consistent with show leds)
![screen shot 2018-10-08 at 9 56 47 am](https://user-images.githubusercontent.com/16690124/46622772-8523c880-cae0-11e8-9665-2a61d5e17e92.png)

@halspeed @jaustin @pelikhan

**Comment by halspeed** [comment]
This looks good @samelhusseini thanks for the quick turnaround.

Can we mute the OFF LEDs in unconnected blocks like in v0:

![image](https://user-images.githubusercontent.com/29285304/46639280-c2ad4380-cb2a-11e8-8b48-45081572da68.png)

![image](https://user-images.githubusercontent.com/29285304/46639297-cfca3280-cb2a-11e8-924d-5c00e815a4f6.png)

**Comment by samelhusseini** [comment]
Issue is fixed.
