### ISSUE TITLE
Inconsistency selecting micro:bit logo v1

### ISSUE THREAD

**Issue by halspeed** [Microsoft/pxt-microbit#1370]
**Describe the bug**
On the homescreen, selecting the micro:bit logo opens a new page at microbit.org/code. In the editor, selecting the micro:bit logo goes to the homescreen.

**To Reproduce**
Select the micro:bit logo on the homescreen and in the editor.

**Expected behavior**
I would expect selecting the micro:bit logo on the homescreen or in the editor opens a new page at microbit.org/code.

**Comment by abchatra** [comment]
This is by design. Students are clicking on the top left expecting it to go to home screen. It used to link out to microbit website in the past. Changed the behavior to take back to the home screen. (Same for all our editors). Top left is usual paradigm to go back. 

Moving the logo to a different location and adding a back or home button at the top left is another solution we discussed. 
For example: Logo removed in Minecraft case

![image](https://user-images.githubusercontent.com/6107272/46819948-d975b500-cd39-11e8-8b25-52566dc2eec6.png)
