### ISSUE TITLE
The LEDs clolor of the blocks now is hard to differentiate.

### ISSUE THREAD

**Issue by soya6598** [Microsoft/pxt-microbit#1433]
**Is your feature request related to a problem? Please describe.**
Wondering why the color was changed.
using white is certainly brighter, but sometimes it also feels like "there's nothing overhere".
likewise, it's totally different from the lights color of micro:bit, maybe a little weird?

**Describe the solution you'd like**
Change to some color that's not white. maybe if pink red, similar as it was.
![-1](https://user-images.githubusercontent.com/42193809/47002845-931cbd80-d160-11e8-8cd9-39eae0d79352.jpg)

**Additional context**
![default](https://user-images.githubusercontent.com/42193809/47001855-07099680-d15e-11e8-928f-9dbf651b5f6c.jpg)

Sometimes is hard to recognize. (maybe for me.) 
fill dark to white? or fill white to dark??

**Comment by abchatra** [comment]
@Jaqster

**Comment by Jaqster** [comment]
Hi @soya6598 - thanks for this feedback.  We changed to white because we heard feedback that the Red/Blue contrast was jarring for a lot of users - there is a known optical illusion effect (https://en.wikipedia.org/wiki/Chromostereopsis) that happens with Red/Blue images.  We could look into a different color (pink?), but we thought white would be the easiest since it matches with the Show Icon block and is the same as how Scratch is displaying the lights.  Notice that the lights in the Simulator are still Red, so that should help people understand what it will really look like on the micro:bit.

**Comment by soya6598** [comment]
thnaks for replying, I've catched up on that.

**Comment by abchatra** [comment]
Per design.
