### ISSUE TITLE
Exponent does not produce correct result on micro:bit

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#1435]
**Describe the bug**
Using these examples in makecode produces correct results 10 ** 0.5 = 3.16, 10 ** 1.5 = 31.62.
On the micro:bit these output as '1' eg 10 ** 0.5 = 1 or 10 ** 1.5 = 1. 

**To Reproduce**
1. Go to 'https://makecode.microbit.org/_54xWWzdztU0F '
2. Click on 'A' see output as integer '3.16'
3. Download and flash
4. See output on micro:bit as '1'

**Expected behavior**
Output on device should be same as in simulator

Mac OS 10.14
Firefox/Chrome

**Comment by pelikhan** [comment]
See https://github.com/Microsoft/pxt-common-packages/blob/57adb80aa7f465aba7204c881c79a519c87c92ce/libs/base/core.cpp#L752

**Comment by mmoskal** [comment]
We need to fix the sim though

**Comment by mmoskal** [comment]
The "fix" will most likely be to make Simulator obey integer semantics not change the hardware behavior.

**Comment by pelikhan** [comment]
One plan is to bring rename Math.pow to Math.ipow to make integer semantics clearer — and maybe have a Math extension with pow/trig functions

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by microbit-mark** [comment]
microbit-support: 21830
Another user reports this issue. Are we able to progress it?

**Comment by abchatra** [comment]
This should be fixed.

**Comment by abchatra** [comment]
This should be fixed.  @microbit-mark  can you please test this. If not I will reopen.

**Comment by CaelCoruscare** [comment]
Here in 2024, this issue is **not** fixed.

![image](https://github.com/microsoft/pxt-microbit/assets/20887356/c879d56b-fa95-4966-90f2-e37d6c3fe174)

In the debugger, the above code results in the same output regardlesss of which button is clicked. The math under Button A correctly resolves to 9.5499etc, which is rounded to 10 in the function. If Button B is clicked, 9.5 gets rounded to 10 in the function.

But on the microbit, clicking Button A appears to output about 1.0 instead of 9.5499etc


Where is the code for the "solution"? I don't see any branches or pull requests associated with this issue?
