### ISSUE TITLE
Snap the Dot Tutorial

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-microbit#1613]
Step 7 - Hint is not displaying in blocks
![step7](https://user-images.githubusercontent.com/22108954/48289195-7607a180-e423-11e8-97f7-a9f355c398f5.PNG)

Game - Add Score and Game Over blocks are not appearing in Toolbox
![snapdot](https://user-images.githubusercontent.com/22108954/48289281-be26c400-e423-11e8-8cdc-c74169d2cb85.PNG)

**Comment by ganicke** [comment]
Hmm, can't repro it, seems to work. Maybe something was fixed in the latest bump:

![image](https://user-images.githubusercontent.com/27789908/48343938-8dfc4280-e628-11e8-84d1-2271d801cb61.png)

![image](https://user-images.githubusercontent.com/27789908/48344098-019e4f80-e629-11e8-8e58-aa51d74a9429.png)

**Comment by ganicke** [comment]
Re-open if repro.
