### ISSUE TITLE
Simple code sample behaves erratically in simulator

### ISSUE THREAD

**Issue by tinfoilhatter** [Microsoft/pxt-microbit#162]
The following code behaves as expected on the micro:bit but not on the simulator, where it seems to go into a loop and flash graphics almost at random.

```
let item = game.createSprite(2, 2);
let item2 = game.createSprite(2, 2);
if (item.isTouching(item2)) {
    basic.pause(500);
    basic.clearScreen();
    basic.showString("BOOM!");
}
```

https://codethemicrobit.com/xkiwppzxvl

**Comment by thomasdenney** [comment]
The issue seems to be that the game library is running [this infinite loop](https://github.com/Microsoft/pxt-microbit/blob/master/libs/microbit/game.ts#L691) which plots the game every 30ms, so when `basic.showString("BOOM!")` is shown it is still attempting to draw the game. I suspect that this might be caused by different behaviour of show string on the device and in the simulator, but I'm going to take a look to see whether the game library does something different.

**Comment by abchatra** [comment]
Ported to pxt repo: https://github.com/Microsoft/pxt/issues/553
