### ISSUE TITLE
Serial Read Line API non-functional

### ISSUE THREAD

**Issue by tinfoilhatter** [Microsoft/pxt-microbit#166]
The Serial Read Line API is not working as expected. I would expect it to read a line of text from the serial console, terminated with ENTER, and return that line. Here's my test code:

```
basic.forever(() => {
    serial.writeLine("What is your name?");
    let answer = serial.readLine();
    serial.writeString("Hello,");
    serial.writeLine(answer);
});
```

https://codethemicrobit.com/zjzwqspyjb

This code prints the first line and then apparently does nothing, even when given input.

The simulator seems to show the **forever** loop above running about a thousand times a minute. Control falls through the **readLine** command as if it were not there at all. I don't have the Enter key held down.

Finally, for what it's worth, **readLine** doesn't seem to be implemented in `/libs/microbit/`.

**Comment by thomasdenney** [comment]
Isn't `readLine` implemented in C++ [here](https://github.com/Microsoft/pxt-microbit/blob/master/libs/microbit/serial.cpp#L32)?

**Comment by thomasdenney** [comment]
The issue here is exactly what your terminal sends when your press enter. The linked function expects a single '\n' character, however I found that by default PuTTY sends '\r'. For example, [this C++](https://gist.github.com/thomasdenney/95b9c4c4737e4dbe79214295dcd36314) (equivalent to your sample) works fine for me with default settings (you are expected to send back \r\n). I haven't tested, but I assume UNIX terminals send '\n'.

I'm not sure what a good solution is here aside from rewriting readLine to fill a buffer until it finds either \r or \n, and then ignoring a \n after a \r.

**Comment by tinfoilhatter** [comment]
I just committed the reference page for this API. I added a the following note. It will be easy enough to delete once your proposed changes (**thomasdenney**) are made to it.

> This function expects the line it reads to be terminated with the `\r` character. If your terminal software does not terminate lines with `\r`, this function will probably never return a value.

**Comment by abchatra** [comment]
Closing for now as there is no action here.
