### ISSUE TITLE
UI bug - can't release a block 

### ISSUE THREAD

**Issue by kdk945tc** [Microsoft/pxt-microbit#1759]
**Describe the bug**
Package:
github.com/DFRobot/pxt-Obloq 
UI bug. 
Works fine with Makecode V0, failed with V1.
The page dead after dragging out a block.

**To Reproduce**
1. Go to 'makecode.microbit.org' add the package 'github.com/DFRobot/pxt-Obloq '.
2. Click on 'OBLOQ'
3. Scroll down and drag out 'on topic received.....'
4. The block cannot be released. 

**Expected behavior**
the block shows up in the coding area.

**Screenshots**
![image](https://user-images.githubusercontent.com/26248125/50393619-5f7a9700-0792-11e9-891a-396650f77e9d.png)

**Desktop (please complete the following information):**
All platform

**Comment by abchatra** [comment]
@riknoll can you please look at this issue

**Comment by riknoll** [comment]
Weird bug! I explain what's going on in the PR. This only affects packages using our old radio destructuring mutator; we haven't used that since we upgraded our blocks so we didn't catch it until now.

The good news is that it shouldn't affect any scripts using the old radio blocks because the bug only shows up when dragging a block out of the toolbox (and we hid those from the toolbox)

**Comment by abchatra** [comment]
Fixed in /beta. Please validate.
