### ISSUE TITLE
All radio receive blocks are permisive

### ISSUE THREAD

**Issue by rhubarbdog** [Microsoft/pxt-microbit#1765]
**Describe the bug**
All radio receive blocks are permissive, well they assume each others identity \
without warning. Block `radio.onReceivedValue(name, value)` acts as a va\
riant block. It receives messages (19 character), integers, doubles and value, \
number pair blocks as 8 chars preceded by an int 32 or a 8 byte double.
Likewise a `radio.onReceivedString(receivedString)` receives the name portion o\
f a sent value and `radio.onReceivedNumber(receivedNumber)` receives the numeri\
c porion of a sent value.

Send value truncates the name to 8 character for and integer and 11 characters \
for a double precision value without warning and only receives 8 regardless of \
what was sent and the `name length byte` is ignored.  When I send a double prec\
ision value/name pair with an over long	name 11	characters are sent but	the
 `name length byte` is incorrectly set to 12

**To Reproduce**
On 2 different microbits, <a href="https://makecode.microbit.org/_9LoATg7jLRtD">on one load </a>these blocks and <a href="https://makecode.microbit.org/_EVELdi6iFhcu">on the second</a> these blocks
on microbit 1 press A this sends a string; `hello world` `0` received
on microbit 1 press B that sends a  number; `` (blank) `-99` received
on microbit 1 press A+B that sends a value pair; `val_pair` `-256` correctly received

**Expected behavior**
Microbit 2 should only receive the data when A+B is pressed on Microbit 1. in the other 2 cases either nothing should happen or the display should scroll an error message.

**Desktop (please complete the following information):**
 - OS: Linux mint 18.2
 - Browser : mozilla firefox
 - Version : 63.0.3

**Comment by rharbird** [comment]
Like @rhubarbdog, I too am experiencing problems with this feature. I am trying to use several name, value pairs for reporting waterflow in ml for a sink in a bathroom :

"this-use-ml" : number
"average-use-ml": number
"total-use-ml": number

I have found that the block radio.onReceivedValue(name, value) does not behave correctly.  I have tried using:

-  3 separate if statements to parse the packet received,
- an if, else if construct and,
- a switch statement.

The code works correctly in the simulator but does not work when uploaded onto 2 boards. I'm guessing now that the problems are likely related to the way in which 'name' is parsed.

This is an extremely useful function for IoT-type applications so I would appreciate it if it could be fixed because I use the micro:bit for teaching non-CS students at undergraduate level and it's really useful!


Kind Regards,


Rae

**Comment by abchatra** [comment]
I am not sure we can filter on the other side on exactly what is received. @pelikhan do you know?

**Comment by rharbird** [comment]
> I am not sure we can filter on the other side on exactly what is received. @pelikhan do you know?

Many internet protocols parse packets received based on a value for packet type in the header. Is this a possible approach?


Rae

**Comment by riknoll** [comment]
The value name you're trying to send is too long. The docs [here](https://makecode.microbit.org/reference/radio/send-value) say the maximum length is 12 characters, but I just tried it and it seems like the max length might actually be 8. I think it changed when we started supporting floating points in the mbit. I'll fix the simulator so that it matches the hardware and update the reference. 

We should also change the send value tooltip so that it actually mentions that restriction; right now the only way to find it is to go into the reference.

**Comment by pelikhan** [comment]
@ganicke can you document the limitations?

**Comment by riknoll** [comment]
Ah, I see, @rhubarbdog was way ahead of me! The limitation is 12 characters for integers and 8 characters for doubles. Right now there's a bug that's breaking that behavior though, which I can fix.

I have to say though, treating doubles and ints differently is not very JavaScript-y. Maybe we should limit the name to 8 characters always?

**Comment by pelikhan** [comment]
I'm fine with that. it would make our code and the documentation simpler.

**Comment by rhubarbdog** [comment]
@abchatra all  packets have a packet type
0 integer
1 value pair with integer 
2 string 
3 
4 double
5 value pair with double.

If the packet id is incorrect for this block type just return to the main loop.

**Comment by rhubarbdog** [comment]
@rharbird
You say your code syops working when on 2 microbit. Are you setting the group with block `radio.setGroup(    )`.

**Comment by rhubarbdog** [comment]
@pelikhan where are the docs I'm the author of a piece of micropython which allows for comms between MakeCode blocks and micropython on the radio

**Comment by pelikhan** [comment]
source of truth: https://github.com/Microsoft/pxt-microbit/blob/master/libs/radio/radio.cpp

**Comment by rharbird** [comment]
Hello,

Yes I was. I can’t retest right now because I’m in a part of the world with no microbits ☹


Rae
