### ISSUE TITLE
Offline app switches to JavaScript when reopening projects

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microsoft/pxt-microbit#1787]
**Describe the bug**
The offline app switches to JavaScript rather than blocks mode when reopening projects, even if you've never used JavaScript mode.

**To Reproduce**
1. Open offline app
2. Create example project (content doesn't matter)
3. Exit offline app
4. Open offline app
5. Re-open the project

**Expected behavior**
Mode to be blocks as per the web version.

**Desktop (please complete the following information):**
 - OS: mac
- Version: 1.2.13 makecode.microbit.org version from about modal.

**Comment by microbit-mark** [comment]
I can recreate this. Are you able to take a look @guillaumejenkins ?

**Comment by microbit-mark** [comment]
@abchatra this would be good to fix prior to release @abchatra It's confusing if you were working in blocks to have it open in JS

**Comment by jwunderl** [comment]
Ah, this looks like the same thing as https://github.com/microsoft/pxt-microbit/issues/1926. This should be fixed with the next release - I can repro the error with the current offline app, but it no longer occurs on new builds -I just waiting till we did a full re-testing of the offline app to confirm.

That said, any projects that were opened previously and converted to typescript by this bug will likely still open as typescript projects the first time (but after converting back to blocks there, they should remain as blocks projects from then on)

**Comment by jwunderl** [comment]
Fixed in released version (v2.0.3)
