### ISSUE TITLE
Importing a GitHub shared project from home screen opens in JavaScript editor

### ISSUE THREAD

**Issue by jonathanhogg** [microsoft/pxt-microbit#1818]
Importing a shared project (*not* an extension) via a GitHub URL opens the MakeCode editor in JavaScript mode with the contents of `main.ts` instead of opening in Blocks mode with `main.blocks`, even if both files are present and included in the `pxt.json` file. This will cause confusion with novice programmers given the URL of a template project to open.

**To Reproduce**
1. Go to https://makecode.microbit.org/
2. Click on the `Import` button
3. Click on the `Import URL...` box
4. Enter a GitHub URL for a repo containing matching `main.blocks` and `main.ts` files and a `pxt.json` file referencing both, e.g., `https://github.com/outputarts/blooming-bots`
5. Click on the `Go ahead!` button
6. MakeCode editor opens
7. Blocks/JavaScript slider at top of window slides to `JavaScript`
8. Editor shows contents of `main.ts` file with the Explorer sidebar open and the `main.ts` file selected

**Expected behavior**
I would expect the editor to open in the Blocks mode showing the contents of the `main.blocks` file instead, as this is the less confusing mode for a novice programmer.

**Platforms:**
I have reproduced this bug using latest Safari on macOS, Firefox on macOS and Edge on Windows 10. The same behaviour is seen in the iPad micro:bit app.

**Comment by riknoll** [comment]
Opening in JavaScript is usually the "safer" option because opening a blocks file will immediately overwrite the `main.ts` when the editor saves. We don't decompile when `main.ts` changes unless the user actually goes back to blocks, so the blocks file can get out of sync with the text file if you're editing in Monaco (but not in the other direction).

Normally, we store the last used editor for the project in the file header (which the user never sees) to prevent those mistakes. I guess we could move that to `pxt.json`, but it seems weird to have an editor maintained field in that file.

The other option would be to add an "open-in-blocks" option to `pxt.json` but that could be problematic if a user decides to convert that project to TypeScript without knowing that field exists.

Maybe we should support `pxt.json` files with no `main.ts`, and have the editor implicitly add one on first save. @pelikhan any thoughts?

**Comment by pelikhan** [comment]
Or if main.blocks is present, we should try to go to blocks with blocks -> js == js

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by riknoll** [comment]
Yeah, that's much easier :smile:

**Comment by abchatra** [comment]
This is fixed.
