### ISSUE TITLE
Feature request: Servo blocks

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1820]
microbit-support:20519
"I do like the continuous servo block from the Servo extension as a more intuitive version than the servo write pin code block.

Two requests
1. Can the 0% command be improved to hold the continuous servo steady without a drifting movement. Maybe this is a continuous servo limitation.

2. Can the continuous servo block be better optimized? The continuous servo speed has differentiation for values 0-20%, but no differentiation from 20%-100%. I assume because the analog pin out code block has a similar profile e.g. 90 +/- 20 degrees has differentiation, but 0-70 degrees and 110-180 degrees has no differentiation. The work around that I use now is to instruct students to scale their outputs to fall within a 0 to +/-20% range. "

**Comment by pelikhan** [comment]
I consoluted with @DaveAtKitronik from KitRonik which helped a lot about getting insights on this (Dave mentionned a guide brewing on the topic).

(1) Continuous servos are subject to drifting. Essentially, the output of the servo is somewhat proportional to the input voltage and there is no feedback mechanism to calibrate. So as your battery voltage level varies, the servo will start to get drift. There isn't much that can be done there besides turning off the motor at 0%. In that case, the motor will stay where it was but it will not resist change. So if you build a crane, that won't work.

I will add a block that "stops" the servo when in neutral position. This would work for a servo used as a rudder of a boat.

When Dave has his guide online, one should be able to dig in deeper into this topic.

(2) We currently linearly map [-100,100] to [0,180] but probably the continuous servo can only really handle [70,110] then it saturates. I will add an api to set the output angle range so that you could do something like
```
setRange(70, 110)
```
and then [-100%,100%] would map to [70,110].

**Comment by pelikhan** [comment]
![image](https://user-images.githubusercontent.com/4175913/53531592-65e60180-3aa8-11e9-8484-320355d85665.png)

**Comment by pelikhan** [comment]
@ganicke could you do a pass on docs afterwards?

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-common-packages/pull/720

**Comment by abchatra** [comment]
Fixed

**Comment by ganicke** [comment]
Docs addressed in: https://github.com/Microsoft/pxt-common-packages/pull/722 and #1890.

**Comment by HyperDuino** [comment]
Setting the range should be reflected in the servo position command. Currently the user gets a conflicting display:

![image](https://user-images.githubusercontent.com/13832091/55822272-1dacfc80-5ab4-11e9-9194-4dd83303a689.png)
