### ISSUE TITLE
Audio blocks aren't producing sound on Safari

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#1899]
**Describe the bug**
Playing notes doesn't produce audio from the browser on Safari

**To Reproduce**
0. On Safari,
1. Open a new project at makecode.microbit.com/beta
2. Add "Play tone Middle C for 1 beat" in "forever" loop
3. Notice that no audio is produced regardless of the mute/unmute state of the simulator

**Expected behavior**
There should be audio. The audio works in Chrome.

**Screenshots**
![image](https://user-images.githubusercontent.com/6453828/53687668-3f180d00-3cec-11e9-8676-f4c6003d787d.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3 (18D109)
 - Browser Safari Version 12.0.3 (14606.4.5)
 - MacBook Pro 2018, i9, 32GB

**Comment by pelikhan** [comment]
It might be that webaudio requires one user interfaction (click) to get started./

**Comment by microbit-mark** [comment]
Not sure if it's changed since this post, https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/ but from the safari developers "Websites should assume any use of <video> or <audio> requires a user gesture click to play. "

In chrome web audio isnt affected by the policy
"By default, the Web Audio API is not currently affected by the autoplay policy. To enable the autoplay policy for Web Audio, launch Chrome with the following internal switch: chrome.exe --disable-features=AutoplayIgnoreWebAudio."

**Comment by darzu** [comment]
Interesting. I tried hitting mute and unmute and it didn't help, but maybe since the sim is in a separate iframe I need to interact with that. I'll try that out.

**Comment by pelikhan** [comment]
Is this a regression? We should have a visual indicator that a note is being played anyway.

**Comment by abchatra** [comment]
This is a issue with safari
