### ISSUE TITLE
Search is broken in IE

### ISSUE THREAD

**Issue by riknoll** [Microsoft/pxt-microbit#1972]
Typing anything into search causes nothing to happen (flyout should open). Looking in the console I see `DataCloneError`. Works on released so this is a regression.

**Comment by jwunderl** [comment]
Same error on safari (mac and ios)

**Comment by pelikhan** [comment]
This typically means that we are using a javascript function that does not exist in the worker and needs to be shimmed.

**Comment by ChaseMor** [comment]
This is was also broken in Firefox and Edge.

The issue was that there was a function called ``toString`` that was clashing with the default ``toString``. This introduced [here](https://github.com/Microsoft/pxt-microbit/commit/aa51b7e014b81c5f2c678ebddb40de2c313945d2), but was later fixed [here](https://github.com/Microsoft/pxt-microbit/commit/bc717471122014a06ac120ef97930453358b16c4).
