### ISSUE TITLE
PNG Export

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#201]
It would be nice if you could export your project as a PNG file for documentation purposes. Sometimes projects are too tall for one screen and so screen shots have to be knitted together.

**Comment by thomasdenney** [comment]
A main purpose of using Blockly at the moment is that it is straightforward to embed elsewhere, so there isn't a need to take screenshots. However, it looks like extracting the XML from Blockly and building an SVG file should be possible, per [this thread](https://groups.google.com/forum/#!topic/blockly/yOW5cQCZSf0) and [this gist](https://gist.github.com/acbart/dcda677555e97b59c1c91554270dc80b). Once you've got the SVG I believe you can render the SVG into a Canvas element, which can then be rendered as a PNG.

**Comment by thomasdenney** [comment]
Turns out it wasn't too difficult :P. If you paste the contents of [this gist](https://gist.github.com/thomasdenney/aa76acb36d47120ee338b3bd96459556) into the Chrome Developer console (with a workspace open), it will generate a PNG file from the workspace and open it in a new tab. There is also a variable at the top for changing the scale factor, so you can generate really high resolution images from it; the image below is rendered at 10x:

![hires](https://cloud.githubusercontent.com/assets/20356546/18276428/c849a176-7442-11e6-8974-396ad7f70f69.png)

Warning: I have *just* tested this in Chrome on Windows, so I can't comment on how well it works elsewhere. @pelikhan I'm not sure we need this as a feature, but we could consider integrating it.

**Comment by thomasdenney** [comment]
After a little more testing I've found that it doesn't work in Safari (not sure why) or Edge/IE (doesn't allow data URIs) but it does work in Firefox if you allow popups for the site and type 'allow pasting' into the developer console.

**Comment by abchatra** [comment]
Download screenshot on right click on block editor pane does this now. Resolving as fixed.
