### ISSUE TITLE
Why have my integers become floats

### ISSUE THREAD

**Issue by rhubarbdog** [Microsoft/pxt-microbit#2014]
**Describe the bug**
I'm developing some blocks compatible software in micropython.  I have an interest in numbers
I have a number INT32_MAX when i subtract from it it becomes a floating point number for no real reason. The problem is the same at INT32_MIN boundary.

**To Reproduce**
flash these <a href="https://makecode.microbit.org/_3DT2fofWk0Vf">blocks</a> to a microbit.  There are differences in what is displayed in the simulator compared to a microbit. Or at least i have previous experience of it.  The blocks produce the following ranges [2147483645,2147483649] and [-2147483649,-2147483645] press button a to see the next number

**Expected behavior**
These are my results:
```
  Expected    	 Actual
  --------    	 ------
         5            4.99998
         6    	      5.99999
2147483647    	   OK
         8.0  	   OK
      	 9.0  	   OK

          9.0 	   OK
      	  8	      8.0000001
-2147483647   	   OK
          6   	      5.9999999
          5   	      4.9999998
```

**Desktop (please complete the following information):**
 - OS: Linux mint 18.2
 - Browser: mozilla firefox
 - Version : 63.0.3

**Comment by pxtravis** [comment]
We support integers between 2^30 - -2^30. This is for tagged integer strategy. Only 31 bits are available to represent number. Any arithmetic operation involving numbers beyond that will be converted to float and the precision won't be perfect.

We can't fix this bug.

**Comment by martinwork** [comment]
It looks like the float (is it 64bit?) is representing the integer accurately, because subtracting or adding 2147483640 before showing on the display displays the correct whole number. Using the remainder on division by 10 also accurately calculates whole numbers that are displayed without decimal places. It appears that the conversion toString isn't doing a good job for floats that represent large integers. #1781 is related.
