### ISSUE TITLE
Radio default group

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#2017]
I'm proposing this idea - Radio Group should be implicitly set by default to group 1.  
So, in a classroom, the default behavior is everyone is broadcasting to each other over the same channel.
When people use the Radio Set Group block in their code, then we assume they are explicitly going to be using different groups to communicate.

**Comment by abchatra** [comment]
+1 @pelikhan I am up for this change. What do you think?

**Comment by pelikhan** [comment]
It is a breaking change. It was designed to avoid random noise from other groups so unless we have a strong reason to change it, i would leave it as is.

**Comment by abchatra** [comment]
How is it breaking change?

**Comment by pelikhan** [comment]
In a classroom, script that used to be mostly independent will now clash on the same radio group.

**Comment by abchatra** [comment]
No one knows that we assign a magic group consists of hash to radio group.

**Comment by abchatra** [comment]
I believe it is not a breaking change. Default group 1 is broadcast group.

**Comment by pelikhan** [comment]
It is a breaking change. Students will start to receive messages from the entire classroom -- this did not happen in the past.

**Comment by microbit-mark** [comment]
I can see the case for this as well as leaving it as is. It's a good starter for a conversation about wireless communication, to think about why we would set a channel to avoid noise and when everyone broadcasts to each other you get the equivalent of a Denial Of Service, so we've used this in cybersecurity lessons before. Be interested in @microbit-giles's perspective.

**Comment by microbit-giles** [comment]
In my own teaching I have used the 'noise' / 'denial of service' effect to introduce the need for groups, using the fact that everyone gets everyone else's message as a learning point, but this is because I have mostly done radio classwork in Python where this, I believe, is the default behaviour. Like Mark I can see cases for both sides of this - a benefit of changing to a default group would be that the experience for users of both MakeCode and Python to be similar.

**Comment by abchatra** [comment]
What is the default group in python?

**Comment by microbit-giles** [comment]
I believe the Python default group is 0: https://microbit-micropython.readthedocs.io/en/latest/radio.html

**Comment by martinwork** [comment]
The automatic group behaviour is such a good idea! If the default is changed, a new block or setting to choose the automatic group behaviour might be helpful.

**Comment by microbit-mark** [comment]
Couple of options: 
- Can we set group to something like 'auto' by default, so people know there's something going on that sets the group automatically
![microbit-screenshot-1](https://user-images.githubusercontent.com/31242877/56973505-e090d300-6b64-11e9-8fb1-6f7da514fc7b.png)
- The issue seems to be something that crops up as part of a classroom activity, so it's not so relevant to change this for people using a couple of micro:bit on their own that just get the magic of radio without having to set a group. Could we look at how we document and teach this better?

**Comment by Jaqster** [comment]
Just spoke with Jonny about this - we're going to push out any major/breaking changes to the Radio Group behavior until the next release when we can get some more user testing.  In the meantime though, let's move the Radio Set Group block to the very top of the drawer so it's more discoverable.

**Comment by abchatra** [comment]
Decided not to break the backward compat .
