### ISSUE TITLE
numbers are being dealt with inconsistently

### ISSUE THREAD

**Issue by rhubarbdog** [microsoft/pxt-microbit#2019]
**Describe the bug**
I was told in another post that integers are 30 bit in make code for microbit. The number (1073741824 + 1) displays on a microbit as 1073741824.9999999 as it does via `serial.writeNumber`. How ever `radio.sendNumber` sends integer 1073741825.  I try to resolve this issue by entering block `tmp = 1073741824.9999999` the block automatically updates to 1073741825. 

**Expected behavior**
I would expect that 1073741824.9999999 can be entered into a block and niot be updated to 1073741825.  And `radio.sendNumber` to send the data that `serial.writeNumber` is displaying.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser :mozilla firefox
 - Version: 63.0.3

**Comment by martinwork** [comment]
Calculations on these numbers work, like subtracting 1073740000 or remainder on division by 10, but conversion to text fails, which is what serial.writeNumber does and radio.sendNumber doesn't. I don't know what happens when you enter 1073741824.9999999!

I think the following numText function works quite generally even with larger numbers.

https://makecode.microbit.org/_5i6Dt9YTcErs

**Comment by martinwork** [comment]
I think this is a bug, not a question.

The fix #862 referenced above may not have been merged correctly as mentioned here: https://github.com/microsoft/pxt-microbit/issues/2192#issuecomment-515121326

**Comment by abchatra** [comment]
Fixed in /beta
