### ISSUE TITLE
Delete sprite does not remove associated parameters

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2036]
**Describe the bug**
microbit-support: 2842
**To Reproduce**
1. Go to 'https://makecode.microbit.org/_AJWhy71JsX0u'
2. Sprite is created, brightness is shown, sprite is deleted, brightness value persists even though there is no sprite on the screen

**Expected behavior**
Associated values should be deleted alongside sprite

**Comment by pelikhan** [comment]
This is by design. When we delete the sprite it is not rendered in the screen anymore and any modification to its value will have no effect.

**Comment by tguneysu** [comment]
Pelikhan,
The issue was about the sprite as a software entity and it's properties. There is no property visible to the coder that defines the existence of any sprite. The fact that the deletion eliminates it from the screen is of very little use in the code. In a game like environment, there needs to be a way  to tell something created in code is still there or not.  Properties of any software entity should reflect its status. Respectfully.

**Comment by pelikhan** [comment]
Something like a ``is deleted`` property?

**Comment by tguneysu** [comment]
Something like it.
Here is an example little program showing the absurdity of what is happening! 
https://makecode.microbit.org/_Jc1W0uii2XPe

Summary: 
- Created a sprite and positioned it at the edge.
- Checking for its "on Edge" status and displaying a "<" if true, in a forever loop.
- Deleted the sprite.
- And it keeps returning onEdge true after deletion !!!!

This cannot be by design !

Thanks for reconsidering.

**Comment by FranklinWhale** [comment]
@tguneysu `isDeleted()` is now available at https://makecode.microbit.org/beta.

**Comment by FranklinWhale** [comment]
Since a deleted sprite is not displayed, it is not possible for it to be ["touching the edge of the LED screen."](https://makecode.microbit.org/reference/game/is-touching-edge).

I think `isTouchingEdge()` should return false if the sprite is already deleted.
