### ISSUE TITLE
Program no longer loads in editor

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2167]
micro:bit support: 22714
**Describe the bug**
Program appears to hang in the editor on any instance of MakeCode [microbit-Receiver.hex.zip](https://github.com/microsoft/pxt-microbit/files/3271225/microbit-Receiver.hex.zip)

**To Reproduce**
Drag and drop attached hex file into makecode. 
Loading wheel spins continuously.

**Screenshots**
Screenshot suggests main.ts file is not found
![3H1nqF3pZlm8Mq26klKk2QN9bq1v_wLoyg](https://user-images.githubusercontent.com/31242877/59182880-c7674300-8b62-11e9-974c-8ab813399f5e.png)

**Comment by jwunderl** [comment]
It seems like the error is that it doesn't like ``main.ts`` being empty - if I'm remembering correctly that will occasionally cause it to fail to load. Doesn't seem to be a regression - it doesn't load in the version it's tagged as being created in (1.2.13). Here's how the files get parsed:

### Source code

```json
{
    "README.md": "",
    "main.blocks": "<xml xmlns=\"http://www.w3.org/1999/xhtml\">\n  <variables></variables>\n</xml>",
    "main.ts": "",
    "pxt.json": {
        "name": "Receiver",
        "dependencies": {
            "core": "*",
            "radio": "*"
        },
        "description": "",
        "files": [
            "main.blocks",
            "main.ts",
            "README.md"
        ],
        "targetVersions": {
            "branch": "v1.2.13",
            "tag": "v1.2.13",
            "commits": "https://github.com/Microsoft/pxt-microbit/commits/5d5b348757b15c6d00f5b7f560fd69592ca29424",
            "target": "1.2.13",
            "pxt": "4.4.7"
        }
    }
}
```

### header

```json
{
    "compression": "LZMA",
    "headerSize": 290,
    "textSize": 660,
    "name": "Receiver",
    "eURL": "https://makecode.microbit.org/",
    "eVER": "1.2.13",
    "pxtTarget": "microbit",
    "comment": "",
    "status": "unpublished",
    "cloudId": "pxt/microbit",
    "editor": "blocksprj",
    "targetVersions": {
        "branch": "v1.2.13",
        "tag": "v1.2.13",
        "commits": "https://github.com/Microsoft/pxt-microbit/commits/5d5b348757b15c6d00f5b7f560fd69592ca29424",
        "target": "1.2.13",
        "pxt": "4.4.7"
    }
}
```

For the most part it otherwise looks similar to an empty project created in v1.2.13:

[microbit-Untitled (10).hex.zip](https://github.com/microsoft/pxt-microbit/files/3273122/microbit-Untitled.10.hex.zip)

except the ``main.ts`` always has at least a space or new line character in it there (even if you actively try to delete them, it will add the space back when it saves):

![2019-06-10 10 47 20](https://user-images.githubusercontent.com/5615930/59215181-701aa000-8b6d-11e9-84c1-e1cd61dceb61.gif)

Will see what we can do about not crashing on empty files, though - might be able to just add an ``|| " "`` somewhere to cause it handle this condition more gracefully?

**Comment by microbit-mark** [comment]
From the user: "I can’t remember exactly but it would have been around the time I created a new function block and added some more serial communication (but both functions and serial communication were already in use for a while). Every time I made an edit I would download the program direct to the bit and then close MakeCode so I could use the serial port and test the new version. "

**Comment by abchatra** [comment]
can't repro.
