### ISSUE TITLE
Larger Arrays (maybe bug?)

### ISSUE THREAD

**Issue by atrus159** [microsoft/pxt-microbit#2383]
I posted in [this](https://github.com/microsoft/pxt-microbit/issues/2185) thread already a week ago, but it seems like this might be a separate issue, so i'm making a separate post for it.

On both the beta and normal branches, I seem to only be able to store a 2D array of up to about 22x5 elements. Any larger and I get a panic 020. This is a problem for me since I am writing a library for the I2C OLED, and I need a way to store a 5x7 text font, and at bare minimum this requires a 94x5 array of bytes for all printable ascii characters, well above the current limit. 

As of about three weeks ago, I was able to store a large enough array, and something seems to have changed. I don't know if this was an intended change or not, so i'm not sure if this is a bug, or if I am asking for a feature, but I would like to be able to store larger arrays.

**Comment by martinwork** [comment]
There does seem to be a new limitation on array size. It looks like the OLED code is within the new limit but appears to see a reduction in total space available.

Here's a simple example: https://makecode.microbit.org/_gYmJ4UFfh4wJ. With this, live and beta support a 106x5 array. V1 will do 171x5. In live and beta, 107x5 causes panic is 844, but I can add a second 32x5 array with matching code. In V1 172x5 causes panic 020 as does adding a second 1x5 array. This seems to show a lower limit on the array size and about 40x5x8 bytes less memory available.

94x5 looks to be just inside the array size limit. If the code at https://github.com/Tinkertanker/pxt-oled-ssd1306 is giving panic 020, it seems likely that the reason it is now out of memory is not the reduced maximum size of array, but less (72x5x8 bytes?) total memory available.

The font data only needs to be bytes rather than 8 byte javascript numbers. Is it possible for it to live in flash rather than RAM? That would release a lot of memory for users of the extension. Could it be managed by some C code?

**Comment by abchatra** [comment]
Store it in the flash like

**Comment by mmoskal** [comment]
See here https://github.com/microsoft/pxt-microbit/blob/master/libs/core/music.ts#L179

```
const fontData = hex `1f00abcd...`
... fontData.getNumber(NumberFormat.UInt16LE, 12) ...
... fontData[24] ...
```

You can use indexer syntax if you need to access one byte at a time, or `getNumber()` if you need 2 or 4.

Another example is here: https://github.com/microsoft/pxt-common-packages/blob/master/libs/screen/text.ts

**Comment by atrus159** [comment]
That actually works really well, thanks
