### ISSUE TITLE
Makecode adds aditional backslash on String when switching to Javascript

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-microbit#2396]
When switching to Javascript, MakeCode adds an aditional Backslash to the String.
![1](https://user-images.githubusercontent.com/37311672/63102038-9d733800-bf7a-11e9-9c60-f8ac712954ce.png)
![2](https://user-images.githubusercontent.com/37311672/63102045-a06e2880-bf7a-11e9-8391-c175648be0fe.png)

It doesn´t make any Problems on the 5x5 mirobit LED-Display but when examening the String and writing to my I2C OLED it causes an error.

**Expected behavior**
Let the String be the same in Blocks **and** Javascript

**Comment by FranklinWhale** [comment]
The additional backslash is added because `\` is a special character in JavaScript. See "Escape notation" in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String

I notice that you are trying to write some bytes to the I2C device. I think you may to do so via `number[]` or `Buffer`.

**Comment by abchatra** [comment]
Javascript needs additional '\' to escape characters.
