### ISSUE TITLE
unable to open hex files

### ISSUE THREAD

**Issue by machinehistories** [microsoft/pxt-microbit#2427]
I have several hex files that I am unable to open in either v0, v1, or beta
the errors range from (network request failed oops something went wrong),
some files only show (oops something went wrong), while others show (Sorry we couldn't recognize this file). I am attaching a zip file with files that have errors. 
[issues.zip](https://github.com/microsoft/pxt-microbit/files/3608910/issues.zip)

**Comment by abchatra** [comment]
3 of the hex (locly.hex. scratch-firmware-combined (1).hex. showio_microbit_BBiJQeKPo.hex) don't have source code in them. This is possible in an edge case. When size of the hex is bigger than what can fit in the microbit, we strip out the source and just keep the hex file. (If the file is saved through save button this shouldn't happen). This edge is only when you download and hex file size is too big.

microbit-oscilli_2.uploaded.hex - this file is dependent on pauldfoster/pxt-microbit-gy521 package, which is not compiling due to size of cpp being too big. 
```js
backend.js:1 Error: Bad HTTP status code: 404 at https://makecode.microbit.org/api/gh/pauldfoster/pxt-microbit-gy521/ee3814ffd2472ba0650ad9861452b0bf93351e81/text; message: {"message":"maximum file size in package is ~64k; file MPU6050.cpp; size 70440"}
```

**Comment by machinehistories** [comment]
I am certain these files all previously worked. Just out of curiosity is
there a way to unpack and look at the contents of a hex file. I don't mind
remaking the files according to the new file size limit but I don't even
remember what these files were and it looks like I have many files that can
no longer load because of their size. I know I used some of these files as
demo files in class and it would really help to be able to see their
contents. Can I run a previous local version of makecode to access these
problem files. Basically what do you suggest as a way to access files that
previously worked. thanks

**Comment by abchatra** [comment]
Does these files work with
makecode.microbit.org/v0
makecode.microbit.org/v1

v0 is unchanged from 2017 Summer and v1 from 2018 summer. If they don't work there, I am not sure how these files are generated.

**Comment by machinehistories** [comment]
I just tested a few files and they opened on V0 so that helps a ton. I am
sorry I didn't realize it was so easy to open up the previous editor.
thanks for your help
