### ISSUE TITLE
wrong block UI of command (array insert value at beginning) and (array remove value at #)

### ISSUE THREAD

**Issue by anakinnet** [microsoft/pxt-microbit#2651]
**Describe the bug**
this two commands in an array box was not correct.
![image](https://user-images.githubusercontent.com/10265839/76547698-3261f380-64c0-11ea-9faa-a4fb1d1dac70.png)
![image](https://user-images.githubusercontent.com/10265839/76547712-3c83f200-64c0-11ea-94b9-b1105b762edf.png)

It's not return the value. it should be rectangle not oval. I cannot place the command in Block mode but I can use it in JavaScript mode.
![image](https://user-images.githubusercontent.com/10265839/76547834-7228db00-64c0-11ea-9700-c1b0c77f1200.png)
![image](https://user-images.githubusercontent.com/10265839/76547924-908ed680-64c0-11ea-93a7-5a0ace73e547.png)

**To Reproduce**
1. Go to 'Makecode'
2. Click on 'Array'
3. Scroll down to 'this two command' and use it as document in help
![image](https://user-images.githubusercontent.com/10265839/76548165-eb283280-64c0-11ea-8fea-5c0fce033a6f.png)

![image](https://user-images.githubusercontent.com/10265839/76548240-0430e380-64c1-11ea-9b56-3c667dd3e0e8.png)

**Comment by jwunderl** [comment]
the error in step #4 is showing up because it's mixing up the type of the variable - if you change it to ``set myNum to list {remove value at 0}`` it will work, it's just trying to put a single number into a variable that was determined to store an array of numbers

The issue here is that a lot of array methods in javascript return values that are commonly ignored / not used, and any function that returns a value currently turns into a reporter (round) block. 
In this case, the unshift returns the length of the array after adding the value, and removeAt returns the value that was removed.

Definitely agree that this isn't ideal though, most commonly annoying for me with `array.pop`.

**Comment by anakinnet** [comment]
Hi jwunderl,

Thanks for the hint. So, I should not expect it will change the shape to rectangle right?
BTW, do you have a list of standard shape/block that you just mention "reporter block".

**Comment by jwunderl** [comment]
I'd say the current behavior is not a bug (it's behaving as intended from the blocks point of view, the javascript API just has a return value that we often don't need), but some way to easily handle the situation of 'call this function and ignore whatever it returns' would be nice -- I run into this one a lot with arrays too.

re: block shape names, I'm actually not sure about a list off the top of my head -- reporter's the one that seems to come up most often. Mainly just know it from reviewing / changing code related to it
