### ISSUE TITLE
Using `parseInt` with a `stringSplit` shows difference between device and simulator

### ISSUE THREAD

**Issue by gbraad** [microsoft/pxt-microbit#2664]
**Describe the bug**
Issue with `parseInt()` difference between device and simulator when used with an array.

**To Reproduce**
1. Go to https://makecode.microbit.org/_6JKYvC8Wh1Xu
2. Click on the simulator (observe 'original' and 'parsed' value)
3. Download to device
4. See error on serial monitor (using P0, P1 in the example)

```typescript
// command is in a larger codebase interpreted with the onDataReceived
let command = "X100\r\n"
let cmdArgs = helpers.stringSplit(command.substr(1, command.length), " ")
serial.writeLine("original: " + cmdArgs[0])
let cmdId = parseInt(cmdArgs[0])
serial.writeLine("parsed:  " + cmdId)
```

**Expected behavior**
Expect for `parseInt` to be consistent.

**Screenshots**
In simulator:
```
original: 100
parsed:  100
```

On device:
```
original: 100
parsed:  0   
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Firefox

**Additional context**
This is normally used in a larger codebase and I need to send the command as `X100 ` instead before this starts to work. it would seem the `split` does not work the same? but when observed, the split does fill the value but parsing fails.

**Comment by Amerlander** [comment]
I had similar issues with parsing serial commands as numbers.
I just tried to receive 1 and 2 digit strings and parsed them as number. 2 digits seemed to work, but 1 digits didn't.

My findings were:
- `typeof parseInt(cmdArgs[0])` returns `NaN` in some cases
- The line endings seem to interfere, but in some cases they don't and `parseInt()` just works
- Since lots of functions are not available in makecode which could help here ( `trim()`, replace by regular expression, `isNaN()`, …) I worked myself around doing a check whether `parseInt()` returns a number greater 0 and if not slicing the last character and just doing the `parseInt()` again:

```
read = serial.readLine()
if (parseInt(read) > 0) {
    readInt = parseInt(read)
} else {
    readInt = parseInt(read.slice(0, -1))
}
```

I'm not sure if this actually has to do with your issue, but maybe it helps in some way. I haven't investigated any deeper in my case.

**Comment by gbraad** [comment]
It looks similar and definetly an issue. over the weekend I will look likely look into this a bit more.

**Comment by gbraad** [comment]
I have worked around with a `trim()`-like function.

However, I do notice the serial connection from the NXP->nRF is not very reliable either.

```
$M0
M0
$
Kitten:bit V3.9
$M0
M0
$
0 Kitten:bit V3.9
$M0
M0
$
bit V3.9
$M0
M0
$
en:bit V3.9
$
```

but when I do a `serial.redirect()` to external pins with an FTDI or CH340, I get the expected results:
```
$ M0
M0 Kitten:bit V3.9
$ M0
M0 Kitten:bit V3.9
```

The rest of the code is identical, except for the serial interface.
Something is not right here...

**Comment by jwunderl** [comment]
trivial repro `basic.showNumber(parseInt("100z"));`; `parseInt` just calls `parseFloat`, and ends up in a call to `String_::toNumber` which handles spaces but not other non num characters as terminators (parse int shouldn't use parsefloat anyways, as that doesn't support `0b1` or `0xa`) -- so looks like a handful of fixes needed here :)

@Amerlander quick note that isNaN is in /beta (it came with constant folding)
