### ISSUE TITLE
"Print" project has blank first page for long projects

### ISSUE THREAD

**Issue by shakao** [microsoft/pxt-microbit#2737]
**Describe the bug**
Example program: https://makecode.microbit.org/_EwucyFH3F1fW

![image](https://user-images.githubusercontent.com/34112083/78084344-c5c67000-736c-11ea-815b-b307e4ebca12.png)

**Comment by pelikhan** [comment]
No repro. 
![image](https://user-images.githubusercontent.com/4175913/78406674-fbab6480-75b7-11ea-819f-0ed92012538a.png)

**Comment by shakao** [comment]
hmm try in blocks/with a function that is longer than one page? or maybe it's a windows thing....

**Comment by pelikhan** [comment]
This behavior is by design. We tell the browser (through CSS) to prefer to keep the blocks together. In this particular case, the blocks barely fit on a full page so the browser decide to skip the rest of the page and have blocks in full scale on the next page. See pdf.

[Microsoft MakeCode for micro_bit.pdf](https://github.com/microsoft/pxt-microbit/files/4430058/Microsoft.MakeCode.for.micro_bit.pdf)
