### ISSUE TITLE
blocks do not properly support text arrays

### ISSUE THREAD

**Issue by shoelacesrcool** [microsoft/pxt-microbit#2749]
**Describe the bug**
When trying to show string (element in text array), blocks will not compile

**To Reproduce**

This javascript works:

input.onButtonPressed(Button.A, function () {
    basic.showString("" + text_list[1])
})
let text_list = ["Vernonia", "Mist", "Hillsboro", "", ""]

If you try to convert to blocks, you get error: Type 'string[]' is not assignable to type 'string'.

Building directly in blocks also does not work.

**Expected behavior**
You show be able to use "show string" block to show an element of a text array

**Screenshots**
![image](https://user-images.githubusercontent.com/62978747/78099848-05ef1800-7398-11ea-829b-22e77654df7c.png)

**Desktop (please complete the following information):**
chromebook, chrome browser

**Additional context**

**Comment by jwunderl** [comment]
I believe this one is the same as https://github.com/microsoft/pxt-arcade/issues/1131, which is fixed in the codebase but the fix is not in the current release; just tested your example and it works in [/beta](https://makecode.microbit.org/beta). The fix will go out to the main site with the next full release.
