### ISSUE TITLE
Left navigation bar is empty in Chinese

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2807]
**Describe the bug**
Left navigation bar is empty in Chinese

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Games-->Reaction Time->Show Instructions

**Expect behavior**
Left navigation bar isn't empty as in English
![image](https://user-images.githubusercontent.com/59192069/78866048-483be780-7a71-11ea-850c-b6b7aff26c79.png)

**Actual behavior**
Left navigation bar is empty in Chinese
![image](https://user-images.githubusercontent.com/59192069/78865991-30646380-7a71-11ea-8a1b-3a2ea542c00b.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.12
3.Microsoft MakeCode version: 5.37.19

**Comment by jwunderl** [comment]
Hm, this is about half fixed with new docs (showing minecraft docs w/ traditional chinese, as the translations are applied in backend / don't work on localhost atm)

![image](https://user-images.githubusercontent.com/5615930/81122539-e6429680-8ee5-11ea-862e-54ffed494610.png)

only the headers aren't getting replaced properly now, so individual links show up. This is probably a pretty quick fix, but it won't be something I can work on for a week or two as I need to wait till I can access a few more things to setup up backend locally :)

**Comment by jwunderl** [comment]
@riknoll if you have time this might be one to grab?

**Comment by riknoll** [comment]
I think the issue with the minecraft TOC was a bad translation, which I have now corrected in Crowdin. Someone translated one of the header tags in the summary.md (not the header itself, but the reference we use for extending summaries). Waiting for the localization to update so that I can test it out.

**Comment by abchatra** [comment]
Resolving this as fixed for now.
