### ISSUE TITLE
Beta: Start/play melody?

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2835]
The play melody block added to Beta could cause confusion as it seems like a duplicate of start melody. I expect this is because start melody is not a block used for other hardware

![Screenshot 2020-04-17 at 17 03 03](https://user-images.githubusercontent.com/31242877/79589466-59b66c80-80cd-11ea-8484-6dba867547fa.png)

Can we consider changing play melody > play sequence?

**Comment by pelikhan** [comment]
Superseeded by https://github.com/microsoft/pxt-microbit/issues/2971

**Comment by jaustin** [comment]
While both blocks are called "melody" I don't think #2971 really resolves this...  Though it does help...

There's some issues with 'sequence' because a lot of starter material describes code as a 'sequence' so avoiding that term is best. 

As this plays a series of notes/tones, I wonder if we could use that terminology?

Where we say "tone" elsewhere in the blocks, we show notes but actually take a frequency... I thought perhaps we could also handle frequencies in the "play melody" block but so far seems not, though I suspect that might be a fun addition? That would make "Play tones" a viable name?

So `music.playTones("262 330 392 440 220 330 262", 120)` or `music.playNotes`

FYI: @microbit-giles
