### ISSUE TITLE
Improve behaviour of "Download to your micro:bit" window

### ISSUE THREAD

**Issue by MTKilpatrick** [microsoft/pxt-microbit#2936]
Every time one presses "download" to produce the .hex file from the Makecode editor, a window appears in the middle of the screen "Download to your micro:bit".

Once you know the flow, this window is rather annoying and it requires a mouse movement and a button click to get rid of it - it obscures the code window.

Can you please put a " don't show this window again" feature to this window and replace it with a very brief pop-up that says "download complete" and then vanishes after two seconds?

**Comment by pelikhan** [comment]
@MTKilpatrick in beta, the recommend flow is to use WebUSB. No more download dialog, no more drag and drop, just fast download directly to the board.
Because of shared computers in schools, we can store any settings locally in the browser. But we could maybe hide this dialog for the life of the project.

**Comment by abchatra** [comment]
WebUSB is the recommended way to use. 

We don't want to change the dialog due to shared computer scenario.
