### ISSUE TITLE
Incorrect bottom margning on side docs

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3014]
![image](https://user-images.githubusercontent.com/4175913/81572041-90437800-9357-11ea-9be3-b2fca6c81400.png)

Occurs when window height is small.

**Comment by pelikhan** [comment]
![screengrab](https://user-images.githubusercontent.com/4175913/81572191-c2ed7080-9357-11ea-8566-170891208484.gif)

**Comment by microbit-grace** [comment]
This issue seems reproducible in current live MakeCode.

**Versions**
makecode.microbit.org version:  [7.0.61](https://github.com/Microsoft/pxt-microbit/releases/tag/v7.0.61)
Microsoft MakeCode version:  [11.1.14](https://github.com/Microsoft/pxt/releases/tag/v11.1.14)
microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
codal-microbit-v2 runtime version:  [v0.2.68](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.68)

https://github.com/user-attachments/assets/cc42d8ac-c6f2-4fa4-9207-bb7b85430e6c
