### ISSUE TITLE
Unify dialogs handling of close icons

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3105]
We have a non-consistent use of close icons in all our dialogs. For example:
![image](https://user-images.githubusercontent.com/4175913/82482580-eae18000-9a8b-11ea-8ac8-d232f862afc3.png)

**Comment by jwunderl** [comment]
To confirm, we should swap cancel for close just when there is no action being taken (e.g. here there isn't anything to do, you're just closing the dialog)? e.g. when deleting a file:

![image](https://user-images.githubusercontent.com/5615930/83081087-ada16300-a034-11ea-8acb-1fcf25c5c0b1.png)

the explicit cancel makes it feel safer / clearer to me then just having a close button, as it's a choice rather than a dismiss

**Comment by pelikhan** [comment]
In that confirm cases, we should keep cancel.

________________________________
