### ISSUE TITLE
Rendering error when hiding/showing the simulator in high contrast mode

### ISSUE THREAD

**Issue by shakao** [microsoft/pxt-microbit#3126]
**Describe the bug**
![image](https://user-images.githubusercontent.com/34112083/82593095-cbfbf000-9b56-11ea-8f5a-35eed99c7ac1.png)

**To Reproduce**
1. Go to editor, select "High Contrast On" from Settings
2. Hide the simulator
3. Expand the simulator, see error.

**Comment by jwunderl** [comment]
@shakao To clarify, were you referring to the white background on the leds as the rendering error? That's actually the expected behavior at the moment / the existing 'accessible mode', as the normal color contrast is way too subtle.

There's a bug here where it's either not getting the high contrast message or not updating correctly when high contrast mode is enabled, though -- will fix that (and maybe worth bringing up in a design meeting if there's a way to make the hc sim look a bit better).

**Comment by shakao** [comment]
oh yeah good to know! yeah the confusion stems from the sim not updating when you enter high contrast, or if it's in HC mode (with the white bg) it isn't re-rendering with the dark bg when you exit high contrast
