### ISSUE TITLE
Feature: Array should remember type when emptied

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3179]
**Is your feature request related to a problem? Please describe.**
When using an array block, if you delete the items in the array and then from an empty array state try to add a new item, the array does not know whether it is a string or number. This can be confusing for kids who do not know how to construct the array.

![Kapture 2020-05-27 at 16 03 08](https://user-images.githubusercontent.com/31242877/83039746-6ae08a80-a036-11ea-96ef-1f6bad47cece.gif)

**Describe the solution you'd like**
Empty array remembers the array type that it was

**Describe alternatives you've considered**

**Additional context**

**Comment by abchatra** [comment]
Won't fix. Empty array has no types and it is not an undo operation when you expand it.

**Comment by Parakleta** [comment]
Related to this it is not possible to create an array of empty arrays because the type information is lost and there is then a typescript error which states "variable 'list' implicitly has an 'any[][]' type".  Even adding the type information in Javascript mode and moving back into blocks doesn't work because the type information is deleted.
