### ISSUE TITLE
Text category broken in Czech

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#3304]
**To Reproduce**
1. Go to 'Blocks->Advanced->Text'
2. See garbled blocks

**Screenshots**
![image](https://user-images.githubusercontent.com/6107272/86035034-7a197600-b9f0-11ea-9933-852ef700839f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge

**Comment by abchatra** [comment]
@jwunderl can you take a look at this issue and help @livcheerful fix these issues in the future.

**Comment by ganicke** [comment]
Looks like https://crowdin.com/translate/kindscript/65/en-cs#937310 might be goofed up.

**Comment by jwunderl** [comment]
Sure, I'll just leave a note here to start so it's easier for future reference?

First thing is just seeing the error; easiest to do in a local build to get non-uglified js, but opening the site is often good enough to get a quick idea of what's messed up:

![image](https://user-images.githubusercontent.com/5615930/86036344-928a9000-b9f2-11ea-8744-47ba0a796689.png)

so that looks like error is in the string `index of` block from the top error; on crowdin, login, find language, and then under the target (microbit here) find `core-strings.json` (or `base-strings`) which contains most of the builtin strings. (if there are other builtin packages you might find other -strings files for the packages, e.g. radio-strings). In there you'll find all the block strings -- including the one galen linked just above: https://crowdin.com/translate/kindscript/65/en-cs#937310 .

![image](https://user-images.githubusercontent.com/5615930/86036982-936ff180-b9f3-11ea-83fa-4c7224a4ca62.png)

In this one, notice that it uses the old `%` syntax for variables instead of `$`; that's important as that one is index based instead of variable name matching (there might be another minor difference I'm forgetting, if in doubt Richard probably has the most context as I believe he wrote the new format). This means that the translation is broken because it got the order on the parameters mixed up. If you look below the translations, there's a `tm and mt suggestions` - the one listed as tm is `translation memory`, so an old version of the translation. that has the things in the right order, so I'll apply that for now:

![image](https://user-images.githubusercontent.com/5615930/86038196-67ee0680-b9f5-11ea-958d-8b2a79d42132.png)

after adding the translation, you have to save it, and then approve it -- that's the check mark next to the translation

![image](https://user-images.githubusercontent.com/5615930/86038433-c31ff900-b9f5-11ea-8d37-da0ea04c56be.png)

Validating changes after the fact is a little bit harder; it won't show up in the editor for ~ a day as the crowdin values are cached. You can step through the breakpoints on translations (e.g. search for `function lf(` or the portions where blocks are translated). Typically easiest is to use Peli's in context translations feature, as that will always pull up to date values as it uses the logged in users account to request the translations; click the bottom left button on the translations page:

![image](https://user-images.githubusercontent.com/5615930/86040333-b355e400-b9f8-11ea-8606-24926fcf031a.png)

select the broken langauge and login, and find the broken translation and see that it works

Important other thing, note the first step on crowdin was selecting the target; this means that if the translation is broken, you'll also want to check other targets to see if they're also broken, as it won't just get copied over automatically :(

(If the translation is wrong and there's no alternative, I'd say just bin it with the garbage can next to it; better to have no translation than a breaking one)

**Comment by livcheerful** [comment]
Thanks, Joey!! I'm going to take a look :D

**Comment by jwunderl** [comment]
Oh, I think this should be fixed now because I fixed it while taking the screenshots, but walking through all the different pages is probably worth while as dealing with translations can be a lot

**Comment by livcheerful** [comment]
ahaha yeah I'll def do that

**Comment by ganicke** [comment]
Previously, I've also pasted a dummy copy of namespace functions into the playground and stubbed them out. Then, replaced the ``block=`` with the translated strings to see if the decompile works out. This easy with simple set of exports but can be more difficult, as in this case, with an interface form.

**Comment by jwunderl** [comment]
oooh that's a good idea yes, just copy over the declaration in the source with a trivial change (e.g. append 1 to the fn name) and explicitly set the block string to the translated one. Both that and in context translation should work ~

**Comment by abchatra** [comment]
Fixed. Please refresh the website once you login to  defeat the cache.
