### ISSUE TITLE
Wrong with text blocks when selecting Norwegian language

### ISSUE THREAD

**Issue by Svein-Tore** [microsoft/pxt-microbit#3311]
When I'm selecting the Norwegian language the text blocks are not there, as shown below:

![wrong_block](https://user-images.githubusercontent.com/16510390/86339978-8bfb5300-bc54-11ea-91a9-bc880247cc24.png)

Only 2 blocks are shown.  The menu is in fact "destroyed".

**Comment by abchatra** [comment]
@jwunderl what can be done to avoid this in future?

**Comment by jwunderl** [comment]
Need to fix validation of block translations so that it rejects (& falls back to english) on any translation that changes parameters that use the $ syntax (names, changing parameter type, changing parameter count, properties, optional status). There is some attempt at this already, but it's either broken, not actually on the right path, or not checking the right properties.

**Comment by jwunderl** [comment]
Okay, lots of broken translations here, will need to double check tomorrow.

Categories that should be fixed tomorrow after translations get pulled down:

norwegian bokmal:
- pins -> more
- text

norwegian nynorsk
- text
- pins

polish
- text

For all three (at least one of the) issue(s) was the text is empty block;

```
%this=text|is empty
```
was getting translated as

```
%this=tekst|is empty
```

in all three, with other errors being similar (e.g. putting a space between % and the param name, etc). All stuff we should be able to catch / throw away the failing translation

**Comment by Svein-Tore** [comment]
Works fine now

**Comment by abchatra** [comment]
Fixed
