### ISSUE TITLE
Serial out via USB not working for Kitronik Data Logging with V2 micro:bit

### ISSUE THREAD

**Issue by AlasdairAtKitronik** [microsoft/pxt-microbit#3495]
**Describe the bug**
When using the Data Logging blocks in the Kitronik Smart Greenhouse extension (https://github.com/KitronikLtd/pxt-kitronik-smart-greenhouse), the data transmit via USB to the computer is not working when using a V2 micro:bit in the beta MakeCode editor.

**To Reproduce**
1. Go to MakeCode and start a new project.
2. Add the 'Kitronik Smart Greenhouse' extension.
3. Write the following program:
![image](https://user-images.githubusercontent.com/36475405/97325459-ec00af80-186a-11eb-9fa7-873806dc90ca.png)
4. Download to the V2 micro:bit.
5. Press button A to start recording data.
6. When the tick appears, press button B to send a single data entry or A+B to transmit all the data. The error is that nothing happens at all.

**Expected behavior**
When B or A+B is pressed, the 'Show console Device' button should appear under the micro:bit simulator. 
Clicking on this will open the serial output viewer.
This is the expected serial output:
```blocks
Kitronik Data Logger
Smart Greenhouse
----------------------
www.kitronik.co.uk
;Light ;
1;255 ;
2;137 ;
3;140 ;
4;146 ;
5;151 ;
6;144 ;
7;137 ;
8;135 ;
9;137 ;
10;160 ;
```
Note: This was tested and works with a V1.5 micro:bit.

**micro:bit version:**

The issue is relevant to V2 micro:bit

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  86.0.4240.111 (Official Build) (64-bit)

**Comment by Gadgetoid** [comment]
I'm having a possibly related issue with enviro:bit where my output to USB Serial is stalling the main loop after just a few updates.

I *do* actually see the first few sensor readings appear over USB Serial immediately following a reset, but it very quickly hard stalls the main loop (I know this because I have LEDs turning on/off as part of the test cycle) and no more updates appear over USB Serial.

Removing the lines that transmit over USB Serial preven the main loop from stalling, and my LEDs will happily blink on/off forever.

Ths is the test code:

https://github.com/pimoroni/pxt-envirobit/blob/bdcf246981ae51cb094877e85758c3ee51e5495a/test.ts#L30-L60

Note: I *only* removed the print to serial, I did not remove the code that requests data from the sensor.

**Comment by pelikhan** [comment]
Please try again with the latest beta

**Comment by pelikhan** [comment]
We've also removed the spurious resets in the webusb layer.

**Comment by pelikhan** [comment]
We've pushed a fix to the serial layer. Please try again with https://makecode.microbit.org/beta

**Comment by AlasdairAtKitronik** [comment]
Tested this and it all looks normal now, thanks.
