### ISSUE TITLE
Can't find any my user extensions

### ISSUE THREAD

**Issue by lioujj** [microsoft/pxt-microbit#3504]
I have made some user extensions before, and they are working fine. But today, I made a new extension, uploaded to github, and I wanted to add it to the Makecode, Makecode always said "We couldn't find any extensions matching "https://github.com/....................".
So I uploaded some extensions to examine the situation, All the extensions were not found by makecode.
What's the problem?
![extension_err](https://user-images.githubusercontent.com/34760803/97443560-2307bb80-1966-11eb-89db-4bf054a8382a.png)

**Comment by abchatra** [comment]
@lioujj this is an issue on our end. We haven't completed our work to move to default "main" branch instead of "master" yet. 
Github default naming change info here: https://github.com/github/renaming

You can wait for us to address the issue, ETA: 8 weeks or if there is an urgency, you can temporarily create a new branch called "master" with the same content as "main" and it should fix the issue. 

Apologies.

**Comment by lioujj** [comment]
My solution is: Make the extension and create repository in makecode. After makecode creates the repository, then it can recognize my extension, then I can upload all my codes to github directly.

**Comment by abchatra** [comment]
This is fixed.
