### ISSUE TITLE
Microbit V2 not detected for WebUSB pairing

### ISSUE THREAD

**Issue by CleoQc** [microsoft/pxt-microbit#3541]
**Describe the bug**
My one and only Microbit V2 is not getting detected for WebUSB pairing. I've tried Chrome and Edge. My V1 has no issue.

**Screenshots**

![image](https://user-images.githubusercontent.com/4965628/97722821-792d4980-1aa1-11eb-9883-41ae5ab8c889.png)

**micro:bit version (please complete the following information):**
V2, with firmware 2.5.4

**Desktop (please complete the following information):**
WIndows 10 Pro, Chrome and Edge

**Comment by jaustin** [comment]
Hi @CleoQc 

Thanks for reporting this...

Is this micro:bit working smoothly wityh drag-and-drop? Could you please post the contents of DETAILS.txt here?

Has this been the case since forever, or did it work in the editor(s) at some point?

**Comment by CleoQc** [comment]
It works perfectly fine with drag and drop - which is my usual approach.
I only tested WebUSB for the first time this morning (with my V2) , so I do not know if this is new behaviour or not, sorry.

```
# DAPLink Firmware - see https://mbed.com/daplink
Unique ID: 9904360249624e450038601900000063000000009796990b
HIC ID: 9796990b
Auto Reset: 1
Automation allowed: 0
Overflow detection: 0
Incompatible image detection: 1
Page erasing: 0
Daplink Mode: Interface
Interface Version: 0254
Bootloader Version: 0254
Git SHA: ec3fec91e815b1fe27cefb8bc4ffa85ca3317502
Local Mods: 0
USB Interfaces: MSD, CDC, HID, WebUSB
Bootloader CRC: 0xdb256cca
Interface CRC: 0xd0f0bacf
Remount count: 1
URL: https://microbit.org/device/?id=9904&v=0254
```

**Comment by microbit-mark** [comment]
Hey @CleoQc. Can you try updating the firmware in MAINTENANCE mode to use the one linked here https://tech.microbit.org/latest-revision/#how-do-i-update-the-firmware-for-the-latest-microbit and see if that resolves it?

**Comment by CleoQc** [comment]
I wasn't too sure which was the latest firmware version for V2, so thanks for the link.

I went through the update, and no change. Neither Chrome nor Edge will pair.

New details.txt:
```
# DAPLink Firmware - see https://mbed.com/daplink
Unique ID: 9904360249624e450038601900000063000000009796990b
HIC ID: 9796990b
Auto Reset: 1
Automation allowed: 0
Overflow detection: 0
Incompatible image detection: 1
Page erasing: 0
Daplink Mode: Interface
Interface Version: 0255
Bootloader Version: 0254
Git SHA: 1436bdcc67029fdfc0ff03b73e12045bb6a9f272
Local Mods: 0
USB Interfaces: MSD, CDC, HID, WebUSB
Bootloader CRC: 0xdb256cca
Interface CRC: 0x5b5cc0f5
Remount count: 0
URL: https://microbit.org/device/?id=9904&v=0255
```

**Comment by jaustin** [comment]
Interesting. Do you mind finding the micro:bit in Device Manager and sharing a screenshot of where it lives, and then the device information screen?  (see https://support.microbit.org/support/solutions/articles/19000089574 )

I don't have a viable explanation for why V2 and V1 devices are bahviing differently right now, so think this could be DAPLink related...

What DAPLink version do you have on your V1 board please? Can we tempt you to try 0254 on your V1 board so we can determine if this is DAPLink or device specific please?

https://github.com/ARMmbed/DAPLink/releases/tag/v0254 - 
[0254_kl26z_microbit_0x8000.hex.zip](https://github.com/microsoft/pxt-microbit/files/5466358/0254_kl26z_microbit_0x8000.hex.zip)

But NOTE: we don't suggest this for general use because of https://github.com/ARMmbed/DAPLink/issues/714

**Comment by pelikhan** [comment]
This is not a MakeCode issue.

**Comment by jaustin** [comment]
@CleoQc feel free to pick this up via help@microbit.org :). Also just noticed you're on the v3.1 URL not /beta, which shouldn't affect it but worth a try!

**Comment by pelikhan** [comment]
@CleoQc you'll be much better serve with the microbit foundation team who's got tons of experience with this part. This is under our (MakeCode) feet and we don't know much about the DAPLink webusb stack.
