### ISSUE TITLE
Python code error in "Crashy bird"

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3579]
**Describe the bug**
**Python** code error in "Crashy bird"

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Games---->Crashy bird----->Show Instructions
3.Scroll down to the final code
4.Copy JS code to the editor and run it
5.Switch to the Python code

**Actual behavior**
**Python** code error in "Crashy bird"
![2](https://user-images.githubusercontent.com/59192069/98085416-44adf900-1eb8-11eb-8ab8-5c39fdeec932.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.0.45
3.Microsoft MakeCode version: 6.0.30

**Comment by abchatra** [comment]
@Sheila111 can you verify if the same issue is in the live editor as well?

**Comment by Sheila111** [comment]
@abchatra  also repro in /live editor

**Comment by darzu** [comment]
Smaller repro:
```py
a = [5,6]
print(a.remove_at(0)) // no error
print(a.remove_at(0).toString()) // error
```

**Comment by darzu** [comment]
This one has been quite tricky. The issue is that removeAt is generic and we don't really handle generics in the py compiler. All cases to date have been worked around with some special handling. I'm going to see if we can't do the same here--special case this in a somewhat general way--but the "real" solution would be to come up with a more strategic map of how type inference in py should work and how generics would fit into that. Without doing some more research on that topic (type checking unannotated code) I feel like I'm working a bit blind here as to how we should solve this generally.

And this isn't the first time. A lot of py bugs like this in the past have taken up a lot of time figuring out solutions that have grown organically and don't fit a general plan for how typechecking should work here.

**Comment by abchatra** [comment]
What does generic mean? I am not sure I understand in this context. Why is the following failing as well? 

```python
b = 20
print(b.to_string())
```

**Comment by darzu** [comment]
Oh interesting, that's a new and unrelated regression. That should work and did work recently so one of my fixes might have broken that.

**Comment by darzu** [comment]
Hmm, I was mistaken it's not a regression, it's like this on the microbit live site.

Regardless I filed a new issue here: https://github.com/microsoft/pxt-microbit/issues/3977
because I believe there are separate underlying issues. I'll fix that one first which might make this one easier.

**Comment by darzu** [comment]
Here's the new simplified repro:
```
let obstacles: game.LedSprite[] = []
basic.forever(() => {
    while (obstacles.length > 0) {
        obstacles.removeAt(0).delete()
    }
    basic.pause(1000)
})
```

The problem is removeAt is generic and we're not properly inferring it's return type as "game.LedSprite"
