### ISSUE TITLE
setAnalogPitchPin retargets audio away from mixer. Is this confusing?

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#3611]
Breaking this out from #3531....

Here's roughly the audio pipeline by default...

<img width="985" alt="image" src="https://user-images.githubusercontent.com/147113/98364686-274c6c80-2029-11eb-8e11-fbfcacee734c.png">
...and after calling setAnalaogPitchPin
<img width="984" alt="image" src="https://user-images.githubusercontent.com/147113/98364720-33d0c500-2029-11eb-96e8-6ac040918d48.png">

I've highlighted in red the things I'm concerned about for users in this case. It is fully V1 compatible, but that isn't necessarily what people might expect! Tricky to work out the right thing to do here.

In the case of #3531 it was useful to bypass the mixer, but only really because the mixer was a source of unexpected noise when allegedly silent, not necessarily a real requirement.

Due to the lazy initialisation of the mixer pipeline, @finneyj if people make sound for the first time *after* calling setAnalogPitchPin do we twist things up?

(These are some quick modification of @finneyj's slides. Thanks Joe.)

_Originally posted by @jaustin in https://github.com/microsoft/pxt-microbit/issues/3531#issuecomment-723048836_

**Comment by jaustin** [comment]
@abchatra tagging as P3 as I don't think this is somethinig that needs urgent attention, but thought it made sense to file it as I'd already written it up for another issue. Not attached to this designation.

**Comment by martinwork** [comment]
Was just about to ask if analogSetPitchPin and setOnBoardSpeakerEnabled should be independent. After analogSetPitchPin, it seems only a reset will enable the speaker. Now I know why!

Here's my test...

```
input.onButtonPressed(Button.A, function () {
    music.startMelody(music.builtInMelody(Melodies.BaDing), MelodyOptions.Once)
})
input.onButtonPressed(Button.AB, function () {
    speaker = !(speaker)
    led.toggle(0, 0)
    music.setOnBoardSpeakerEnabled(speaker)
})
input.onButtonPressed(Button.B, function () {
    pin0 = !(pin0)
    led.toggle(0, 4)
    if (pin0) {
        pins.analogSetPitchPin(AnalogPin.P0)
    } else {
        pins.analogSetPitchPin(AnalogPin.P1)
    }
})
let pin0 = false
let speaker = false
speaker = true
led.plot(0, 0)
pin0 = true
led.plot(0, 4)
```

**Comment by AlasdairAtKitronik** [comment]
@jaustin Having looked at the diagrams a bit more, it seems like this means that all the new V2 sound stuff with the synth and mixer is only ever available on P0 - if the setAnalogPitchPin redirects everything. Is it possible for the other micro:bit pins to be able to access this stuff as well?

**Comment by finneyj** [comment]
Presenting the mixer output on other pins is perfectly possible @AlasdairAtKitronik. (Duplicated on up to four pins in fact if you really wanted to!), but you're right, there's no API for it surfaced in MakeCode yet. Fully agree that we need to agree the correct API for this 

If I understand correctly, we currently have:

On v1:
- P0 is the default audio output pin, which is enabled when any audio is used.
- a ```setPitchPin``` block to change that to any other defined pin

On v2:
- P0 is the default audio output pin, enabled when any audio is used, along with the built-in speaker.
- a ```setPitchPin``` block that brings v1 compatibility only behaviour to any other defined pin
- An enable/disable block for the built-in speaker

To me, this is indeed confusing. 

Wearing my academic hat, and designing top down from a UX perspective for a moment (rather than bottom up from a compatibility perspective), I'd suggest something more like:

- A ```set sound output pin``` block that control the output of the sound blocks, irrespective how it is generated. This could be called set pitch pin for compat if we really wanted to.
- A ```set super sounds``` block that enables or disables the whole audio pipeline above. When disabled, only v1 APIs work (others NOP), and output is driven by a root frequency PWM to the pin defined by ```set sound pin```. When enabled, everything goes through the mixer pipeline. By default this is enabled, and this block hides in the "more" section of its tray, as it will not be often used.

If I was being really blue sky (pretending v1 never existed for a moment), I'd also question whether or not we would even route sound output to P0 at all by default. I strongly suspect we would decide not to, and only route sound to an edge connector pin if ```set sound pin``` was called...

Just my 2p to promote discussion!

**Comment by DaveAtKitronik** [comment]
would the `set sound output pin` block list pins that are capable and 'internal' to enable / disable the onboard buzzer?
If you are routing the sound out of the board its for use externally, so disabling the onboard device makes sense I think.

**Comment by pelikhan** [comment]
What about adding a new API to control the output pin in the mixer? It allows use music/tones/sounds with the mixer on different pins. Speaker already an API to turn on/off

``setSoundOutputPin(pin: Pin, on: boolean)``

We need a ``setPin(pin: Pin)`` and ``setPinEnabled(on: boolean)`` on the MicrobitAudio.

The ``setAnalogPitchPin`` turns on legacy PWM modulation as it is now. This would be used with Piano or when PWM squares are needed.

**Comment by pelikhan** [comment]
https://github.com/microsoft/pxt-microbit/pull/3720

**Comment by jaustin** [comment]
I've tested on V1 and V2 with the new block, and it works. Main issue for me now is that I don't think that block belongs in the V2 categoery... it works fine on V1 and it looks like it replaces setAnalogPitchPin so should live somewhere V1 users can pick it up. I propose renaming 'Volume' to 'Output' and putting the new block there. ("Output" is a good name for that as it now also contains 'stop all sounds' which isn't really volume related)

I think the most likely thing a user is going to want to do with this block though, is select 'none' which I think they currnently can't. Because for someone using the speaker, I think it's reasonable to say "I don't want sound on the pin" but I guess the current way to do that is just to use the pin as something else using the 'pins' blocks?

Final thing, because this affects melody blocks and 'ring tone' etc, I think it shouldn't be called `set sound pin` but  `set audio pin` or `set music pin` where I prefer audio.

**Comment by pelikhan** [comment]
https://github.com/microsoft/pxt-microbit/pull/3723

**Comment by abchatra** [comment]
Fixed
