### ISSUE TITLE
Shake overlaps with microphone in v2

### ISSUE THREAD

**Issue by riknoll** [microsoft/pxt-microbit#3616]
<img width="388" alt="Screen Shot 2020-11-06 at 11 20 07 AM" src="https://user-images.githubusercontent.com/13754588/98406113-40055400-2022-11eb-9f47-a38ca667578f.png">

**Comment by jaustin** [comment]
In the past it was also possibe to wobble the mouse a lot on the sim to shake it. Was that an old TouchDevelop feature? IIRC also shake a tablet or phone would work?

**Comment by pelikhan** [comment]
It's still possible to shake the mouse and trigger the shake event or in fact, any of the events. We map the mouse position to a quadratic force field.

We decided to not use the phone/ipad accelerometer. Mostly to keep this consistent but also because shaking the device triggers "undo" events in iOS which are very annoying.

**Comment by jaustin** [comment]
The undo thing makes sense, thanks for lettting me know :). I didn't realise wobble-to-shake still worked - macOS makes my pointer large before it shakes but can confirm it's great and does work for me, especially easy if I go diagonally.
