### ISSUE TITLE
Regression: accelerometer input not updating after boot (working on 3.1.28, not on 3.1.29)

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#3654]
**Describe the bug**

The accelerometer values don't update after initial values.

This is a regression. Looks like it occurred between 3.1.28 (works) and 3.1.29.(does not)

@finneyj it looks like the major change between those versions is V0.2.17 for the CODAL

**To Reproduce**
<img width="351" alt="image" src="https://user-images.githubusercontent.com/147113/98826334-76314200-242d-11eb-981e-46bc6c45945c.png">

Accelerometer doesn't update after first read. Moving the device and using reset shows the value is initially read.

**Expected behavior**

Device constantly updates accelerometer valie

**Comment by jaustin** [comment]
@martinwork could you please take a look in CODAL and see if you can see where this regression occurred? We think it might be the default pull affecting I2C lines, perhaps?

**Comment by pelikhan** [comment]
Default pull down on pin constructor?

________________________________

**Comment by finneyj** [comment]
I think i see it - default pullDown on IRQ line. Looks to be correctly configured here:

https://github.com/lancaster-university/codal-microbit-v2/blob/master/source/MicroBitAccelerometer.cpp#L65

but irq1 in that class seems to be defined as a copy of uBit.io.irq1 rather than a reference, so may be getting overridden by the default later...

@martinwork - you can leave with me?

**Comment by martinwork** [comment]
@jaustin 
@finneyj Happy to leave with you!

**Comment by pelikhan** [comment]
Pulling

________________________________

**Comment by pelikhan** [comment]
v0.2.19 on its way in v3.0.54

**Comment by finneyj** [comment]
thanks @pelikhan

**Comment by pelikhan** [comment]
v0.2.19 shipped. Please reopen if issue persists.
