### ISSUE TITLE
"Export code..." option as image in vectorial format

### ISSUE THREAD

**Issue by ngammarano** [microsoft/pxt-microbit#3713]
## Is your feature request related to a problem? Please describe
Sometimes it is needed to share an image of the MakeCode code. Taking screenshots is annoying and many times end with bad resolution or badly cropped blocks. It would be great to have an option to download a vectorial image (e.g. svg, eps, emf) of the code. This is particularly useful for the students to embed their code (or part of it) in a report (e.g. a doc file).

## Describe the solution you'd like
In MakeCode editor, in the menu, add an option "Export code...", this option would enable to download an image of the code in vectorial format like svg (there could be more than one format to choose).

For example, in [this MakeCode project](https://makecode.microbit.org/_8K4PxHepP1rp), the output svg image would be:
[on_start_show_string_it_works.zip](https://github.com/microsoft/pxt-microbit/files/5538911/on_start_show_string_it_works.zip)

**Comment by jaustin** [comment]
This would be really useful, but there is a workaround for now too.

If you use the MakeCode code embedding tool (https://makecode.microbit.org/blocks-embed ) then you can print the page and get a nice PDF from it.

Here's an example of me opening the PDF printed from [JSFiddle](https://jsfiddle.net/nq0hyz97/) in a vector graphics editor. I had to pretend I had an A1 sheet to get this output but that's just because I printed direct from the fiddle to get this.

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/147113/99296045-16c49f00-283e-11eb-8273-f25046a08058.png">

Note that printing directly from the editor or the editor embed iFrame gives you black-and-white blocks not nice coloured blocks. Less good for posters.

**Comment by ngammarano** [comment]
Thank you, that is exactly what I have been doing.

I used that JSFiddle and in HTML rendered the desired MakeCode project. Then, in the browser: left click on the blocks > "Save as..." and saved in svg format.

**Comment by martinwork** [comment]
From the iOS micro:bit app, you can get a PDF, by choosing Print... from the more/cog menu.

Wait for the content to load, then tap Print (NOT the share button).

In the iOS Printer Options dialogue there is a hidden hidden feature... Do a reverse pinch gesture to expand a page. This results in a new display with a share button for a PDF.

**Comment by jaustin** [comment]
> Thank you, that is exactly what I have been doing.
> 
> I used that JSFiddle and in HTML rendered the desired MakeCode project. Then, in the browser: left click on the blocks > "Save image as..." and saved the blocks image in svg format.

Thanks for the tip, that saves me a step!

**Comment by ngammarano** [comment]
@jaustin If you're interested, [I've modified the JSFiddle and the HTML a little bit](https://ngammarano.github.io/RenderBlocks.html) to be able to write code in JavaScript or paste the MakeCode project ID and generate the blocks in svg to save.

**Comment by abchatra** [comment]
Work around exits.
