### ISSUE TITLE
Toolbox not appearing in Microsoft Teams for MakeCode assignment

### ISSUE THREAD

**Issue by microbit-pauline** [microsoft/pxt-microbit#3789]
An Educator using the MakeCode micro:bit app on Microsoft Teams has noticed an issue where the simulator has loaded but the blocks are missing.

We are unable to test this. 

**User Image**
![image](https://user-images.githubusercontent.com/29146842/100866243-4acfcf00-3490-11eb-8009-aa1ea00aed23.png)

Support ticket https://support.microbit.org/a/tickets/41201

**Comment by Jaqster** [comment]
This is the read-only view that shows up once an assignment has been turned in.  Can you ask the user to give us the repro steps for how they got to this view?  And confirm they are signed into Teams with a Teacher account?

**Comment by livcheerful** [comment]
@microbit-pauline should I be able to access the support ticket? It seems to redirect me to login every time I try :\

**Comment by Jaqster** [comment]
Thanks Pauline.  I'm following up with the Teams team.

**Comment by Jaqster** [comment]
Hi Pauline - here's the update from the Teams team:
"This is by design,  In the "Student View" that the teacher accesses, the resource is read-only. That view is intended as a sneak peak, and teachers are meant to do their editing in the "Edit Assignment" view. Is there a user need to edit from the "student view"?"

So, the reason the Teacher doesn't see the Toolbox is because they have already Assigned the assignment, so it's in read-only mode.  But the students who open the assignment will see the Toolbox and be able to edit it.  Hope that helps!
