### ISSUE TITLE
current version of Bluetooth extension start to cause conflict and don't know how to solve

### ISSUE THREAD

**Issue by sbb777** [microsoft/pxt-microbit#3903]
**Is there any way to use old version Bluetooth extension with the online makecode editor? such as configuring the  pxt.json file for my extension?**

**Describe the bug**
The block coding which was written about 20 days ago, it still ok to complie,
but yesterday I got ‘Some extensions will be removed’ warning when I  tried to add Bluetooth extension after inserting another extension which had been OK.

**To Reproduce**
I just tested for more simple way.
(Steps to reproduce the behavior:)
1. Start a new project (makecode)
2. add Neopixel extension
3. try to add Bluetooth extension
→ this will cause ‘Some extensions will be removed’ warning. (about 20 days ago it was OK)

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

So I removed the neopixel part from my own extension, 
then I could add the Bluetooth extension.
But during compile I got an error.
'msg = bluetooth.uartReadUntil(serial.delimiters(Delimiters.SemiColon))'
'Problems1 Line 8: !!proc || !bin.finalPass'
(I need to parse several information from BLE uart communication.)

**Comment by abchatra** [comment]
Bluetooth and neopixel extension doesn't work with each other. This is due to hardware limitation. You can add only one of them.

**Comment by sbb777** [comment]
Thanks for answer.
Could I ask two questions more?

(We plan to avoid the simultaneous use of Neopixel and BLE with your answer.
But we have already created a code and teaching plan that uses Neopixel and BLE extensions together. In fact, Neopixel and BLE Extensions together are currently being used still.

I did not know the exact cause, but the old version of Neopixel extension can be used with BLE extension now. When I was writing, I thought the BLE extension has changed, but it seems that one of the Neopixel and BLE extensions has changed.)
 

1. You said there is a hardware limitation. Can't use Neopixel and BLE together for both Microbit version 1 and version 2 ?
Is the hardware limit due to the lack of timer interrupts?

2. According to the tests, the Neopixel extension of the old version of about a year ago and BLE can be used together. When will this type of use(I mean last spring version of Neopixel and BLE) become impossible ? I think there is a deadline for using dal and codal, so I asked.

**Comment by abchatra** [comment]
@microbit-carlos will be able to answer these questions?

**Comment by microbit-carlos** [comment]
I believe the main reason Neopixels don't work well with bluetooth is because BLE configures interrupts that can interfere with the neopixel bit banging and cause issues.

As far as I understand, MakeCode stops the use of BLE with the neopixels extension via this configuration in pxt.json:
https://github.com/microsoft/pxt-neopixel/blob/master/pxt.json#L30-L34

It looks like that configuration hasn't changed in the last 5 years, so if that works now in V1 then it's possibly an issue in MakeCode?

As far V2 goes, CODAL can now drive Neopixels via the PWM peripheral, so it should be able to work with Neopixels, but that would probably require an update to the pxt extensions, which I assume in V2 are still banging in assembly?
