### ISSUE TITLE
Add WebUSB Download Notification toast for v2 blocks on v1 micro:bit

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4090]
Add a user notification (toast, popup dialog?) on Download button clicked when:
- User has micro:bit v1 paired via WebUSB
- User program contains v2 blocks

Say something like "Your project contains code that only works on the new micro:bit.  Learn more" maybe link to https://microbit.org/new-microbit

**Comment by riknoll** [comment]
@soniakandah can you take a look at a design for this? I'm leaning towards an alert because a link in a toast message is gonna be tough to "catch" before it disappears.

Also, do we have code for doing this detection already @pelikhan?

**Comment by pelikhan** [comment]
When connect, yes we do know the version

**Comment by soniakandah** [comment]
@riknoll do you still need anything for this?

**Comment by riknoll** [comment]
@soniakandah it would be nice to get an image!

**Comment by soniakandah** [comment]
Here is the specific image for this modal, but if you check issue #4092 you can see all the other images in the web usb flow redone. @riknoll free feel to update those images at your own pace, it's not crucial. 

![WebUSB_04](https://user-images.githubusercontent.com/22336391/121954616-d239ad00-cd13-11eb-821e-a7ad35f922e7.png)

**Comment by soniakandah** [comment]
Comments from our team's design sync: 

- For all the modals with side-by-side text and image, let's vertically center both the text and image
- For the modal with two columns of image on top and text below, let's top align each column's text blurb so they are at the same height 
- For modals with images on the right side of the modal, crop the image from the right so that there's no white space on the right

@riknoll for visibility
