### ISSUE TITLE
Background frame of "new? Start here!" is not fit when high contrast on

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4100]
**Describe the bug**
Background frame of "**new? Start here!**" is not fit when high contrast on

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Click **High Contrast On**

**Actual behavior**
Background frame of "**new? Start here!**" is not fit when high contrast on. Some part of it are extra.
![image](https://user-images.githubusercontent.com/59192069/119456939-bcb51100-bd6d-11eb-8c34-ac08585275d4.png)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.85
3.Microsoft MakeCode version: 6.13.39

**Comment by jwunderl** [comment]
Ah I fixed this as a side effect when I was fixing the line height behavior in https://github.com/microsoft/pxt/pull/8188 ~

![image](https://user-images.githubusercontent.com/5615930/119545083-400f3c00-bd47-11eb-9a6e-887dac541b2b.png)

(note there will be a bit extra when there is multi line as paragraphs don't trim width in that case, but that's expected behavior

![image](https://user-images.githubusercontent.com/5615930/119545207-6b922680-bd47-11eb-8006-f1275505e777.png)

(that is, it will only be a tight fit like the original image when it's < 1 line long, but that is expected / valid)
