### ISSUE TITLE
"My Projects" should not be clickable

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4127]
**Describe the bug**
"**My Projects**" should not be clickable

**Steps to reproduce the behavior**
1.Nabigate to https://makecode.microbit.org/beta#
2.Click "**My Projects**"

**Expect behavior**
It can't be clicked 

**Actual behavior**
"**My Projects**" should not be clickable. It should be same with other catalogs such as "**Tutorials**".
![3](https://user-images.githubusercontent.com/59192069/119958437-a01b1200-bfd5-11eb-96a3-05412d69672c.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.87
3.Microsoft MakeCode version: 6.13.42

**Comment by jwunderl** [comment]
This is expected behavior / by design. Originally it was the only part that was clickable / there wasn't a view all button, but we added that to make the project explorer view easier to identify. We left the click on the `My Projects` words intentionally to make sure the click target was as easily accessible as possible for users who want to use the projects view
