### ISSUE TITLE
'Export data' in console view does not respect csv formatted output

### ISSUE THREAD

**Issue by riknoll** [microsoft/pxt-microbit#4167]
Using this program: https://makecode.microbit.org/_ML4hEXD5iKb0

When I downloaded the csv from the simulator, it ended up looking like this:

```
sep=	
time (source1)	Time (seconds)	time (source1)	x	time (source1)	y	time (source1)	z
0	0.05	0	0	0	0	0	-1023
0.074	0.051	0.026	0	0.026	0	0.032	-1023
0.1	0.15	0.105	0	0.105	0	0.105	-1023
0.149	0.199	0.165	0	0.165	0	0.165	-1023
0.239	0.259	0.225	0	0.255	0	0.255	-1023
0.299	0.349	0.315	0	0.315	0	0.315	-1023
0.359	0.409	0.375	0	0.375	0	0.375	-1023
0.449	0.469	0.435	0	0.465	0	0.465	-1023
0.509	0.559	0.525	0	0.525	0	0.525	-1023
0.572	0.622	0.585	0	0.585	0	0.585	-1023
0.659	0.679	0.645	0	0.675	0	0.675	-1023
...
```

For some reason there are 5 columns for time

**Comment by jwunderl** [comment]
Dropping from next-release for now; we're now outputting the same as the hardware to the serial view:

![image](https://user-images.githubusercontent.com/5615930/122452096-bd505a00-cf5d-11eb-988a-c58e821a3428.png)

The issue is that the 'export data' button tries to infer columns and is messing that up / ignoring the header. The 'copy text' button works as a workaround to download as a .txt that you can switch to be a csv and then everything 'just works'

**Comment by abchatra** [comment]
I think still the bug exists. 
See this program: https://makecode.microbit.org/_XWz3tk2rcTMM

Either we can introduce a new copy & download button above console log, or can have a secret message to skip everything.

**Comment by microbit-mark** [comment]
When I use the download button with the data from the example in https://github.com/microsoft/pxt-microbit/issues/4167#issuecomment-863666850 , I get a duplicate column for time.

![image](https://user-images.githubusercontent.com/31242877/141965298-78d2b841-bc19-4758-a260-fa92255ef444.png)

Is this the same bug? It tripped up at least one user in our data logging user study.
