### ISSUE TITLE
iOS app back button is broken

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#4202]

**Comment by shakao** [comment]
https://github.com/microsoft/pxt/pull/8261
https://github.com/microsoft/pxt/pull/8262
https://github.com/microsoft/pxt/pull/8263

will close after foundation verifies that the message passing works

**Comment by martinwork** [comment]
Thanks @shakao. The message passing is working. A very quick, light tap sends "backtap", and a long hold sends "backpress"

But there seems to be a middle ground that doesn't send a message, even though there is a click sound.

And the click sound only plays once for each load of the site. I see this console output sometimes, which I think is new... I haven't been able to pin down exactly how that relates to the lack of click. I'm not too bothered about the click, to be honest!

```
2021-06-28 16:19:33.148280+0100 microbit[2151:1881070] [assertion] Error acquiring assertion: <NSError: 0x283d74960; domain: RBSAssertionErrorDomain; code: 2; reason: "Client is missing required entitlement"> {
    userInfo = {
        RBSAssertionAttribute = <RBSLegacyAttribute: 0x100352030; requestedReason: MediaPlayback; reason: MediaPlayback; flags: PreventTaskSuspend | PreventTaskThrottleDown | WantsForegroundResourcePriority>;
    }
}
2021-06-28 16:19:33.148373+0100 microbit[2151:1881070] [ProcessSuspension]  0x10e0acd98 - ProcessAssertion() PID 2151 Unable to acquire assertion for process with PID 2151
2021-06-28 16:19:33.148449+0100 microbit[2151:1856377] [ProcessSuspension] 0x10e0acd98 - ProcessAssertion::processAssertionWasInvalidated()
2021-06-28 16:19:33.150127+0100 microbit[2151:1881070] [assertion] Error acquiring assertion: <NSError: 0x283d7a640; domain: RBSAssertionErrorDomain; code: 2; reason: "Client is missing required entitlement"> {
    userInfo = {
        RBSAssertionAttribute = <RBSLegacyAttribute: 0x1004b4db0; requestedReason: MediaPlayback; reason: MediaPlayback; flags: PreventTaskSuspend | PreventTaskThrottleDown | WantsForegroundResourcePriority>;
    }
}
2021-06-28 16:19:33.150208+0100 microbit[2151:1881070] [ProcessSuspension]  0x10e0acde8 - ProcessAssertion() PID 2151 Unable to acquire assertion for process with PID 2190
2021-06-28 16:19:33.150272+0100 microbit[2151:1856377] [ProcessSuspension] 0x10e0acde8 - ProcessAssertion::processAssertionWasInvalidated()
2021-06-28 16:19:33.663166+0100 microbit[2151:1856377] irmViewMakeCode didReceiveScriptMessage
2021-06-28 16:19:33.663414+0100 microbit[2151:1856377] irmViewMakeCode messageHostWithDictionary {
    cmd = backpress;
}


```

**Comment by abchatra** [comment]
@martinwork Shannon is OOF. We can fix the edge cases later. If this is sufficient please ship the update to the app.

**Comment by shakao** [comment]
@martinwork oh! hmm, so currently the code is set up to send the "backtap" on a "click" event and "backpress" after 750ms (and and nothing if the user lifts their finger before 750), i can change this so it sends a "backtap" if the press is anywhere <750ms--would that be your expected behavior?

**Comment by martinwork** [comment]
@shakao I think the short answer is "yes". I think you noted that the iOS time seemed quite small, so chose 750ms. I'm inclined to agree - we don't need the menu to appear by accident - though the "Min Duration" on the old back button long press gesture recogniser was 0.5s (the default, I expect). I'm wondering what triggers the click sound when neither backtap nor backpress is sent.

Background... I've just had a play with:
- a simple iOS back button with a single choice in the app
- a Safari back button with single and multiple choices
- a custom button in the app that has tap and long press actions (Share on the app's Flash page).

There doesn't seem to be any dead time between tap and long press with any of these. The simple back button seems to show the menu quite quickly, even when there is only one menu item, but fires that item if the touch ends quickly. The safari button also seems to open the menu quite quickly, but doesn't fire the single entry.


It looks like the following two issues are not specific to the back button, and also apply in Safari:
1) If I long press twice, the second time doesn't make a click sound. Also happens when selecting blocks.
2) A long press slightly to the right (i.e. on the Microsoft logo) triggers the menu shown below.

![IMG_0456](https://user-images.githubusercontent.com/989126/125320518-b38afe00-e333-11eb-93ae-4621f811db2d.PNG)

**Comment by shakao** [comment]
oh man, thanks so much for the in-depth breakdown! okay yeah, that sounds right to me--so a tap or press of any length less than 750ms will be a "backtap", and anything greater than that will be a "backpress"! i'll put out a PR for this and i can separately look into the click sound--it is interesting, since this element isn't a button of any kind and we're not triggering the sound, so it might be some kind of default safari behavior for elements with click events registered?

**Comment by martinwork** [comment]
Ah, so the sound is not expected, and the fact that it only happens once makes it less of a problem. Maybe MakeCode is doing something that makes iOS want to make a sound.

I would say the empty box and picture menu for a long press on the Microsoft logo is the more important one to fix. Long press on the micro:bit logo is the same. In contrast, the home page banner picture is not available for download.

Also note that a tap on the micro:bit logo does Home, which happens on Windows too.

**Comment by shakao** [comment]
i've got the update for the short "backtap" event here: https://github.com/microsoft/pxt/pull/8292

and hmm, okay, so i think the white box is the default iOS behavior for a long press on an image--it looks blank because the microsoft/micro:bit logos are white and iOS displays the image on a white background. it doesn't happen on the banner because that's set as a background image, not a direct image in the page. i'm trying a few things to see if i can prevent this

**Comment by shakao** [comment]
you should be able to test the updated backtap/backpress behavior here! https://makecode.microbit.org/v4.1.5

**Comment by martinwork** [comment]
Thanks @shakao! It seems OK now in v4.1.5.

It can still happen, with a press and release for a certain time, that it doesn't go back and no menu appears. The chevron is left enlarged. But it's quite a knack to get the timing right, and only seems to happen when it's the first action after loading the page, so it seems to have something to do with the click sound.

The one-time click sound has been there for some time:
- https://makecode.microbit.org/v2 (v2.0.18) doesn't make the sound;
- https://makecode.microbit.org/v3 (v3.0.68) does.

**Comment by abchatra** [comment]
Fixed in /beta.
