### ISSUE TITLE
math.random incorrectly decompiled to blocks

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-microbit#43]
We should reconsider -- or -- deprecate the difference of semantics between blocks and js.

**Comment by thomasdenney** [comment]
So the issue here is by the API between blocks and JS. The block selects a random number in `[0..limit]` but the JS API selects a random number in `[0..limit)`. The compilation to JS deals with this, but the decompilation to blocks doesn't, so when it compiles the blocks to JS to check that the blocks are the same as the JS, and in this case they won't be:

1. Create a random block for 0 to 4
2. Code generated is `Math.random(5)`
3. Block generated is `Math.random(5)`
4. New JS generated is `Math.random(6)`
5. `Math.random(5) != Math.random(6)` therefore throws an error

**Comment by thomasdenney** [comment]
Fixed [by this commit](https://github.com/Microsoft/pxt/commit/fc62a0963a011b1c4ef85577fd19079a19980a97)
