### ISSUE TITLE
Differences in icons between live/beta

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4465]
Side by side. Thanks @jaustin 

![62A85297-9E8A-4973-8F1D-4D10BE64B35B](https://user-images.githubusercontent.com/31242877/152137461-decea5d6-4127-4e06-a472-ec0703656587.jpg)

The obvious differences are Input and calculator. Is this an incoming change?

## Beta
![image](https://user-images.githubusercontent.com/31242877/152004766-bb85436f-2a0f-408e-b1ee-774744c7e176.png)

## Live
![image](https://user-images.githubusercontent.com/31242877/152005180-bde657e9-dafc-4eb6-a9d2-fb11e9eb97fa.png)

**Comment by abchatra** [comment]
This is due to upgrade of dependencies like semantic UI + fontawesome. There are the new icons from these libraries. Won't fix from our end. They are pretty similar to the old icons and shouldn't be blocker for students.

We have a separate issue for Serial icon missing https://github.com/microsoft/pxt-microbit/issues/4499
