### ISSUE TITLE
Compass values in sim increase in anti-clockwise direction

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#4471]
https://support.microbit.org/a/tickets/51003 (private), 
https://support.microbit.org/a/tickets/51422 (private) and 
micro-bit community Slack https://microbit-community.slack.com/archives/C226FGXQX/p1645639608795929

**Describe the bug**

> We are using blocks in makecode to create a compass following the NCCE Teach computing unit. When we use the compass emulator and manually move the compass (directional arrow) the degrees displayed go from 0 to 360 in an anti clockwise, we expected the degrees displayed to  move in a clockwise direction 0-360, with 90 being at a 3 o clock  position.
> However when we download to the microbit it appears to display and move as expected on the independent microbit

**To Reproduce**
1. Open https://makecode.microbit.org/_fFXAsqC25FWK taken from https://teachcomputing.org/curriculum/key-stage-2/programming-b-sensing/lesson-4-finding-your-way
2. Rotate compass in sim
3. Compass values increase in anti-clockwise direction

**Expected behavior**
Compass values increase in clockwise direction

**Screenshots**
![Screen Recording 2022-02-08 at 04 20 21 pm](https://user-images.githubusercontent.com/31242877/153032917-3b5a1070-bdac-4ab7-b894-98149988a128.gif)

This change looks to have been introduced in https://github.com/microsoft/pxt-microbit/pull/4442 but is confusing teachers and students

The v2 editor exhibits the experience that the teacher expects
<img width="494" alt="Screenshot 2022-02-08 at 16 30 16" src="https://user-images.githubusercontent.com/31242877/153033257-5883f21f-5aca-4b06-b7c3-2a76c403ab3a.png">

**Comment by abchatra** [comment]
This might be related to https://github.com/microsoft/pxt-microbit/commit/822c0c1dd5e99ddecf27d1a7b972815e02081d90

**Comment by Amerlander** [comment]
> When we use the compass emulator and manually move the compass (directional arrow) the degrees displayed go from 0 to 360 in an anti clockwise, we expected the degrees displayed to move in a clockwise direction 0-360, with 90 being at a 3 o clock position.
However when we download to the microbit it appears to display and move as expected on the independent microbit

@riknoll, @microbit-mark In the simulator the device is fix and the direction of north changes. In the real world you change the device and the poles are fix.

Please check this program, which shows a compass needle: https://makecode.microbit.org/_XHVfKX3sga99

In the current stable version, it behaves natural on the simulator. In the current /beta it does not, since the display does not fit with the user input and the simulator feels pretty buggy (but the program is correct in real life).

So I highly recommend reverting the revertion back.
