### ISSUE TITLE
sound effects: currently no indication of variables in the field editor

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#4551]
The expanding block alongside the field editor works really well as a balance of letting people explore/discover what the parameters do, and then set the programatically. However, at the moment when values are set using variables, these aren't clearly reflected in the field editor.

It would be good to indicate to users that a value that's 'overridden' by a variable is being approximated/demonstrated in the field editor.

For example in this program here it might be confusing when a user doesn't hear the same sound on their micro:bit as they 'tested' because the values are different (the simulator will help here, of course)

![variables-in-fieldeditor](https://user-images.githubusercontent.com/147113/164325068-52b8ba97-cea5-43df-977a-620a4cbe9fbe.gif)

Would something like the following be possible @riknoll ?
<img width="514" alt="image" src="https://user-images.githubusercontent.com/147113/164326059-adcd2664-248f-401f-9548-7538d1f2aed1.png">

**Comment by riknoll** [comment]
We played around with a solution for this when doing user testing:

<img width="330" alt="Screen Shot 2022-04-20 at 2 34 46 PM" src="https://user-images.githubusercontent.com/13754588/164326815-52a49e97-b199-42f0-807f-385a431bd5ea.png">

IIRC (@unthinkmedia correct me if I'm wrong) the feedback we got was that no one really understood what "simulated" meant (or even really noticed it).

Putting the actual blocks on the graph is not possible, unfortunately, because there could be any number of nested blocks in those inputs. e.g.


<img width="807" alt="Screen Shot 2022-04-20 at 2 38 05 PM" src="https://user-images.githubusercontent.com/13754588/164327215-0ebcc8db-5069-4b68-aaba-5d2eb629a1e8.png">

I think this is a pretty reasonable code snippet since acceleration needs to be remapped to be usable here

**Comment by jaustin** [comment]
Yea, that's a very reasonable example. (I didn't actually deliberately avoid that 'map' being in the sound block in my example, and could have saved myself some time if I'd noticed it...)

I think it's important we do *something* to hint what's going on, but appreciate the extra complexity now.

Thinking aloud... showing the code of the nested blocks is going to be confusing (
`Math.map(input.acceleration(Dimension.X), -1024, 1023, 1, 5000)` isn't what a block user is expecting!) so that really only leaves us with hinting that the selected value is not what will happen at runtime.

<img width="513" alt="image" src="https://user-images.githubusercontent.com/147113/164331089-6d8e2b74-f8b3-4e9e-8f3c-87fa5cd6f7b5.png">

keen for any other ideas @unthinkmedia !

**Comment by JohnVidler** [comment]
Is it maybe worth being a bit 'in your face' about this, and having something like an on-hover tooltip on the handles affected, if we do something like @jaustin 's last suggestion; just to make a user pause as they get a new UI element appear?

**Comment by abchatra** [comment]
Won't fix. There is no feedback from students\teachers this being issue.
