### ISSUE TITLE
Scaling issues with Recent Project cards on Home Page

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#4557]
Edge, Windows, Surface Pro

When I pin Beta to a half-screen view, it looks like the Recent Project cards aren't scaling correctly.
In this view Beta is on the left and Prod is on the right:
![image](https://user-images.githubusercontent.com/22108954/164576467-4ce23eb6-1c57-469e-873c-373ee10341dd.png)

**Comment by jwunderl** [comment]
This appears fixed in beta; new project card size is consistent with the size of the other scripts; I wanna say this was fixed in the arcade release but I don't have the pr handy 
![image](https://github.com/microsoft/pxt-microbit/assets/5615930/a4c00997-5835-4a6b-9936-a4332f7b7c39)
![image](https://github.com/microsoft/pxt-microbit/assets/5615930/8ab8908e-683e-4093-a0ad-204c227c320e)
