### ISSUE TITLE
Replace bread crumbs in extensions with the tab to be consistent

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#4592]
UI design: Instead of breadcrumbs it is better to show the extensions as new tab update 

**To Reproduce**
1. Go to 'Extensions'
2. Click on 'Robotics' or Search for an extension

**Screenshots**
![image](https://user-images.githubusercontent.com/6107272/165397640-37c393df-77f1-404c-8673-e972bc71f6ce.png)

Instead: 
![image](https://user-images.githubusercontent.com/6107272/165397952-a158304a-2415-41f5-87a2-2250475835f0.png)

**Comment by abchatra** [comment]
@unthinkmedia

**Comment by unthinkmedia** [comment]
What problem would this address?  If we start to incorporate filtering
(possibly in Arcade), it may start to get a bit busy. That being said, if
you have a problem in mind that I am not aware of, let me know.

**Comment by abchatra** [comment]
Issue we discussed in the testing is the transition from tabbed UI to breadcrumb and going back is jarring. To go back to original view, one has to click on the breadcrumb.   You can try in /beta

How does breadcrumb help with filtering?

**Comment by unthinkmedia** [comment]
This feels redundant to me and a bit confusing since that one tab functions
quite differently than the others.  It is actually almost functioning as a
header.  The other thing that I notice is that once you select a pill, then
given it is above the tabs I would expect the tab to only include things
inside of the selected section so for example. Show me only
recommendations for LEDs.


[image: Apr-28-2022 10-59-13.gif]

**Comment by Jaqster** [comment]
Is "Installed" and "In Development" also filters?  In general, I think we should try to be consistent about how filters show up across our product.  What's the design pattern in other Microsoft products?

**Comment by unthinkmedia** [comment]
I wouldn't consider "In Development" a filter.  That is more like My Assets
and Gallery pattern. Something that I created and not publisher provided.
I see installed being a state. The original design had installed as the
first lane in the recommended view.  I would be fine removing that and
reverting back to that approach.  That would remove all the tabs, because
we could find another place for in development since that is an advanced
setting.  It doesn't need to be so pronounced. I will whip something up
tonight for feedback

**Comment by pelikhan** [comment]
If you hide it when empty, you basically solve the problem for all/most beginner/intermediate users. Advanced users who build libraries won't mind.

What does it mean by the way, which scripts are supposed to end up there?

**Comment by unthinkmedia** [comment]
We:be removed the need for tabs since it is only required when a person has
local github repo.

**Comment by aznhassan** [comment]
We no longer show the "In Development" (now "Local") tab if there are no such projects:
![image](https://user-images.githubusercontent.com/6496798/170387215-95e43306-df6a-48ab-8b1d-01a72198fb6c.png)
