### ISSUE TITLE
Translations missing and cant be fixed in crowdin

### ISSUE THREAD

**Issue by Amerlander** [microsoft/pxt-microbit#4904]
**Describe the bug**
There are some translations, that are missing in german, spanish and some more languages.

- "remainder of %1 / %2" is not translated. Should be "Rest von %1 ÷ %2"
- "serial write buffer" is not translated. Should be "seriell|schreibe Zwischenspeicher %buffer"

![image](https://user-images.githubusercontent.com/3764089/211352227-02e7cb0c-64fc-44df-9426-ae386dda5c4d.png)

They seem to be translated in Crowdin, at least the remainder block - I could not really tell what string has to be translated for the serial block.
https://crowdin.com/translate/makecode/32/en-de?filter=basic&value=0#q=remainder

The remainder block in https://arcade.makecode.com/#editor is translated.

**To Reproduce**
1. Open makecode.microbit.org/ or makecode.calliope.cc/
2. Change language to German or spanish
3. Check the translations in the Math and Serial blocks.

**Comment by MKleinSB** [comment]
missing remainder string in crowdin @ganicke ?

**Comment by jwunderl** [comment]
These few missing translations appear to stem from blocks that have been changed in the code but not released yet. in particular this one is annoying with the remainder block, as that one is defined in pxt -- where the translations are shared between editors to reduce load / forgotten translations -- and is a bit of a 'special case'  -- typically we avoid these issues by adding new blocks and deprecating the old ones.

If you check in /beta the translations are all fixed there, so they will be fixed when we do the next big release. For future cases, we should either 1. leave the old lf in the corner temporarily when we change strings, and get rid of it once that change has propagated to all editors, or 2. actively hotfix these sorts of minor string changes into the editor, so we don't have translations 'go missing' for months.

(I'm gonna remove the milestone from this one since it's complete in beta, but leave it open for the moment as we probably need to make a policy sorta decision on handling this issue better going forward @abchatra )

![image](https://github.com/microsoft/pxt-microbit/assets/5615930/0f31a0ad-a532-41b5-b61c-cbefcece8920)

**Comment by abchatra** [comment]
This is fixed.
