### ISSUE TITLE
Changing language to Italian sets all play tone block notes to Middle C

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#4905]
**Describe the bug**
Changing language to Italian sets all play tone block notes to Middle C

**To Reproduce**
1. Go to '[...](https://makecode.microbit.org/)'
2. Click on 'New project'
3. Ensure language is English
4. Add some 'play tone' blocks, with various notes
5. Change language to Italian
6. See error

**Expected behavior**
play tone blocks retain their note values when the language is changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/989126/211398352-a5aa8278-5b6f-420c-82f4-9fccea268d5e.png) 
![image](https://user-images.githubusercontent.com/989126/211399374-07cb91f6-1449-4419-9c5d-77b16494702b.png)

**micro:bit version (please complete the following information):**
not hardware related

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 108

**Comment by kimprice** [comment]
This also happens when going from Italian back to English.

**Comment by jwunderl** [comment]
I believe the issue was https://crowdin.com/translate/makecode/65/en-it?filter=basic&value=0#17298 swapping the field name (name to note). I added a check to discard translations that broke things a few years back but it must be missing a case for this one, easiest to start looking from there: https://github.com/microsoft/pxt/blob/addWebUsbDisabledHelpButton/pxtlib/service.ts#L765

Note that fixing this will probably mean notes break in italian, so we'll most likely want to add an upgrade rule in this check: https://github.com/microsoft/pxt-microbit/blob/master/editor/patch.ts#L45 (and probably fix by making `hasEquivalentParameters` reject this block rather than fixing the translation, cause getting rid of the broken translation I linked will immediately break all those projects)
