### ISSUE TITLE
Extension won't load on iPad

### ISSUE THREAD

**Issue by JackAtKitronik** [microsoft/pxt-microbit#4959]
**Describe the bug**
Having trouble loading the kitronik-simple-servos extension on iPad.

"I succesfully used the extension on desktop and Android, but my students will have iPads and unfortunately when clicking on the extension, nothing happens and the extension screen resets itself.

I tried to load other extensions and most of them seem to be working fine on the iPad."

See issue [here](https://github.com/KitronikLtd/pxt-kitronik-simple-servo/issues/5)

**To Reproduce**
1. Go to 'makecode.microbit.org'
2. Create a new project
3. Click on 'Extensions'
4. Search 'servos'
5. Scroll down to 'kitronik-simple-servos'
6. Click on the extension to add it to the project
7. The extension isn't added to the project

**Expected behavior**
The extension should be added to the project

**Screenshots**
See video [here](https://photos.app.goo.gl/FWzqbw54UcYMaHeQ9)

**micro:bit version (please complete the following information):**
It's not hardware related

**Smartphone (please complete the following information):**
 - Device: iPad Air (second generation)
 - OS: Updated as far as possible (15.7.3)
 - Browser: Safari
 - Version: Unknown

**Additional context**
Reporting a bug found by another user

**Comment by jwunderl** [comment]
Issue appears to be virtual keyboard dismissing on blur, clearing search state, and removing the button before the click is registered on the extensions button

**Comment by jwunderl** [comment]
For reference, this can be repro'd on all other devices as well with a slightly different path:

1. open extensions page
2. type in servos, press enter
3. type in an extra letter (no enter) - e.g. make it `servoss`
4. scroll mouse wheel
5. click on any extension

The issue appears to just be the text input blur causing it to update the underneath the click before it 'goes through'; we could hack this away quickly by adding a short client side debounce to the search (e.g. 25-50ms) but that's a pretty bad workaround. Might just be able to move around the phase the event runs in (e.g. make the button trigger onmousedown instead of onclick), have do double check event resolution order between blur and the event that triggers the blur.

![search-blur-bug](https://github.com/microsoft/pxt-microbit/assets/5615930/4d7ff2d4-9ce7-4c45-89fd-3478e597196f)
