### ISSUE TITLE
Tutorial layout: directions area should be taller

### ISSUE THREAD

**Issue by kimprice** [microsoft/pxt-microbit#5016]
See the height in the Clap Lights tutorial. Regardless of screen size, the height is too small to show the footer without scrolling.
I think we should aim to fit the footer, especially for directions that fit on one line.
![image](https://user-images.githubusercontent.com/15070078/227597506-b80e0070-4e1b-4023-882d-2ddc3c4cab3a.png)

**Comment by thsparks** [comment]
Hmm, this isn't a actually one line of tutorial content, since "2. Setting up the sound input", "Reacting to Sound", and the blank new line underneath those are all also part of the content here. We also don't want to take up too much space in the workspace. On the most common MakeCode screen size, we only have this much to work with:

<img width="681" alt="image" src="https://user-images.githubusercontent.com/69657545/227600173-80f03415-e079-444c-ac29-2ae28f8015c7.png">

I think we may want it to expand to fit a title + 2 lines of text without scrolling, but 3 might be too much.

**Comment by thsparks** [comment]
Hmm, this isn't a actually one line of tutorial content, since "2. Setting up the sound input", "Reacting to Sound", and the blank new line underneath those are all also part of the content here. We also don't want to take up too much space in the workspace. On the most common MakeCode screen size, we only have this much to work with:

<img width="681" alt="image" src="https://user-images.githubusercontent.com/69657545/227600173-80f03415-e079-444c-ac29-2ae28f8015c7.png">

I think we may want it to expand to fit a title + 2 lines of text without scrolling, but 3 might be too much.
