### ISSUE TITLE
MY_DATA file isn't generated if logging data on hardware

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#5072]
**Describe the bug**
**MY_DATA** file isn't generated if **logging data** on **hardware**

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#
2. **Tutorials for the new micro:bit(V2)**----->**Cat Napping** and finish it
    Or you can import the project URL in beta version: https://makecode.microbit.org/_Uc1F1sPHMATD
3. Download the project "**Cat Napping**" to the hardware **V2**
4. Press **button A** to **log data** on **hardware** for a while
5. Plug the hardware into computer and see whether **MY_DATA** file is generated under **MICROBIT**

**Actual behavior**
You can see **MY_DATA** file is generated under **MICROBIT**

**Expect behavior**
**MY_DATA** file isn't generated if **logging data** on **hardware**

**Screenshot**
No **MY_DATA** file under **MICROBIT**
![image](https://user-images.githubusercontent.com/59192069/234166148-fdffca25-a598-447c-a95f-c7ae46e02584.png)

**Additional context**
1.OS: Windows11
2.makecode.microbit.org version: 5.1.21
3.Microsoft MakeCode version: 8.6.27

**Comment by Sheila111** [comment]
Attach the file under **MICROBIT** 
**DETAILS.txt:**
[DETAILS.TXT](https://github.com/microsoft/pxt-microbit/files/11316138/DETAILS.TXT)
**MICROBIT.html**:
https://microbit.org/get-started/user-guide/overview/

**Comment by jwunderl** [comment]
Mine seems fine, so I'm curious what could be going on here as well: 
<img width="262" alt="image" src="https://user-images.githubusercontent.com/5615930/234345002-6698db54-30ed-47d9-ad63-59f9c1ff0f92.png">
I tested on the 3 micro:bit v2's I have on hand, though all of them have a bit newer firmware (the oldest I have is running Interface Version: 0255 where yours is listing 0254 in details.txt)

If I remember correctly the first version 'shipped' to consumers for v2 was 0255, @Sheila111 could you try updating via https://microbit.org/get-started/user-guide/firmware/#micro:bit-v2 and see if that works? (and since you'll have to check while you're there, it would be useful to know the hardware revision you have -- should be either v2.00, v2.20, or v2.21 I believe, it shows where to look for it on the website. You might need a magnifying glass 🔎)

**Comment by Sheila111** [comment]
@jwunderl I have updated Interface Version to **0255**, and then it works now. So the cause for this bug is the version of my hardware is old and needs to be updated?

**Comment by jwunderl** [comment]
Yeah, if that worked, there's nothing else we can really do here, just a firmware issue / need to update.

**Comment by Sheila111** [comment]
got it, thanks for your explanation..
