### ISSUE TITLE
‘Download’ button in the dialog is confusing 

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#5116]
**Describe the bug**
‘**Download**’ button in the dialog is confusing 

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#
2. Create a project
3. Plug your microbit to computer and click **Download**
4. **Pair** the device and **connect**

**Actual behavior**
‘**Download**’ button in the dialog is confusing. It seems that it will download the code to microbit as soon as you click on this button in the dialog.

**Expect behavior**
What about renaming this button to '**Ok**' or '**Go to download**'?

**Screenshot**
![image](https://user-images.githubusercontent.com/59192069/236429879-b06ef830-f635-4565-8cbf-b358cf90a46a.png)

**Additional context**
1.OS: Windows11
2.makecode.microbit.org version: 5.1.25
3.Microsoft MakeCode version: 8.6.31

**Comment by abchatra** [comment]
@jwunderl is this by design?

**Comment by jwunderl** [comment]
Yes, by design as it will download at this point, as this is the case where they have paired at the start of the download flow and so pressing the button will 'continue to download'

When I get a look at implementing the progress bar for the 'full download' I can see about making it pop the loading screen earlier / right after this dialog so there's no delay between clicking and starting the loading screen maybe? But it does what was stated as expected behavior currently (immediately starts the process to download).
