### ISSUE TITLE
Inconsistent pairing experience if you choose 'Pair now' after downloading as a hex

### ISSUE THREAD

**Issue by microbit-lucy** [microsoft/pxt-microbit#5130]
**Describe the bug**
In the download flow, if you first choose to download as a file and then choose to 'Pair now' from the 'Download complete' dialogue, the dialogues are slightly different. 

- The 'Download as a file' option is not offered via the Pair now route (maybe this is intentional?)
- The button on the final screen in the flow is labelled 'done' not 'download' (the copy in the dialogue refers to the pressing the download button).

![image](https://github.com/microsoft/pxt-microbit/assets/102724242/4a310fb9-1710-49f4-bc27-41b8fb785b7d)

**To Reproduce**
1. Go to MakeCode BETA
2. Click on 'Download'
3. On step 2, select 'Download as a file'
4. In the download complete dialogue choose 'Pair now' and follow the flow.

**Expected behavior**
The main download flow and the flow accessed via 'Pair now' in the download complete dialogue should be the same.

**Comment by abchatra** [comment]
@jwunderl by design?

**Comment by jwunderl** [comment]
Yeah, it's by design; the context for the two entries into the pairing flow is different. When you press download and we enter the flow that way, 'download as file' is there as an escape hatch; it's not needed in the other pairing flow / just a distraction as that flow is **just** for pairing, and they've already chosen to click into it over clicking 'Download as file' in the pop up that opened the dialog 
![image](https://github.com/microsoft/pxt-microbit/assets/5615930/61a29dac-3cea-4c75-9510-9fc5a2d74293)

The download button is similar; when you've started the pairing flow as a 'download' action it ends with the device being flashed as that's the thing you asked for, but when you only click 'connect device' it doesn't end in a download as it's just been asked to 'connect device'. The wording does refer to clicking the download button for the fast downloads in the future, but that's primarily referring to the main download button in the editor / the wording is mostly left unchanged in this pop up from the current live site's flow. I could give it a shot at differentiating a bit more between the two cases with something like 'the next time you click download...' in the 'pair only' case if we want that?

**Comment by abchatra** [comment]
Additional information not given.
