### ISSUE TITLE
migration path from `start melody <builtin melody>` to `play <builtin melody>` is not clear

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#5219]
**Describe the bug**

The refactoring of the various `play <stuff>` blocks doesn't leave a clear and obvious choice for people following tutorials that use the old `start melody` block (not the 'play melody' block, that's fine).

There are a lot of tutorials, not least on microbit.org including videos that use the existing 'start melody' block. We have asked a number of authors about this and one reason for it's popularity is the ease of conveying a specific tune in text/pictures - something that's much harder with the 'play melody' block that is entirely visual. (Eg, if you want a 'yes' and a 'no' sound people use 'jump up' and 'jump down', but it's much harder to quickly convey that with the visual 'play melody' sequencer)

It's important to us that people following older books and tutorials can still find their way after the changes, and there are two things that I think stand out in making this difficult.

1. The wording ('melody' is now lost)
2. The default behaviour is changed from async to sync

**proposed solutions**

**1. the word 'melody' is not present** in the replacement for the old 'start melody <named melody>' block, so both 'start' and 'melody' are missing. 
--> I propose we resolve this by finding a way to insert 'melody' into the new block structure:

Original:
<img width="375" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/147113/475a8741-d5a3-4de5-9eab-09d97018e6f4">
New:
<img width="289" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/147113/6dd57416-902e-473a-800a-0d9de43e2037">

Proposed to resolve this:
<img width="293" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/147113/494dd95e-4fe4-4e98-b16d-d4f468bb86a3">

**2. The default options are different (blocking vs no-blocking)**
As per #3823 we have long had a weird difference in default behaviour between 'start melody' and 'play melody' ( I think justified by the different language - starting (in background)?). Ultimately it was a bit unclear.

This change causes more confusion now though, because the default for the new `play melody <built in melody>` block is that it blocks, not plays in the background. 

Here's an example of something that will change:
OLD - dancing note animation during melody:
<img width="216" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/147113/c009161d-82bf-43d8-942a-65bfa2503e5b">
NEW - animation plays after song.
<img width="238" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/147113/966b7b5a-d09c-4474-8796-8a49ff6b57b7">
By changing the default of the 'new' block to 'in background' when using a built in melody, we could probably resolve this well enough.

Like so:
<img width="615" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/147113/b2dc8a60-293e-42dd-9556-fa9520e1daa6">

I think these two changes would be enough that someone could now clearly find the 'new' block (start melody --> play melody) and it would work the way their tutorial expects.

I'm not sure what to do about the 'forever in background' option. I'd be inclined to deprecate it as think it's not widely used. Given that we no longer have the 'once' or 'forever' blocks we could do the following just to get the block language more similar. I think I'd prefer not to do this last bit (IE add 'once' ) as it just adds more words.

<img width="1074" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/147113/da484eed-c8a8-4414-8b93-92902676eb3c">

@microbit-giles @whaleygeek would welcome your feedback on this as long-time users of 'start melody'

**Comment by abchatra** [comment]
@jaustin  1. Makes sense (to add melody text to the shadown block). @thsparks working on it.

2. Looks like the once in the block parameter is supposed to be in the foreground and there seems a bug in live if it is not blocking foreground thread. See the documentation help.
<img width="302" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/6107272/5952e8db-a443-414a-8ec5-f9842a6da7d3">

**Comment by whaleygeek** [comment]
@jaustin Thanks for tagging me in on this one. I hadn't realised there was an issue, to be honest, until you raised it here!

I wrote ten lessons using the music blocks here: https://github.com/thinking-binaries/microbit-wearables which is probably the biggest chunk of work I have done recently with the music blocks - and all of these were sounds and tunes and combinations of the two, triggered from gestures. Take a look through the programs and see if that supports or denies any of your assertions above, perhaps?

The other thought I had was, do we have an official 'deprecation process' in MakeCode - I think really any block should really always work even if deprecated, but perhaps a special shading of deprecated blocks with a help link that goes to a page explaining what the better method to use and why, would help. As a guiding principle, where possible, any program that has ever been written and any resource that has ever been printed, should still work ad-infinitum, if at all possible. But we can visually signpost people towards using 'better' or 'clearer' blocks as they become available I think.

Also, some of the new stuff surfacing has background functionality, perhaps you should take a look across anything that has a foreground/background concept, and make sure that the concept is consistently applied across all things as well? background is a relatively complex topic for young children to understand, because they don't have a mental model of concurrency as such. They have a concept of 'at the same time-ish' that they inherit from the fact that scratch supports multiple 'when' blocks, and that sort of translates to multiple forever blocks in MakeCode. But I'm not sure they understand what background actually means, conceptually. And the curriculum focuses on sequence, selection, iteration, with no real coverage of any concurrency.

**Comment by whaleygeek** [comment]
@jaustin As a side question, do we have any resources that even explain what the 'background' concept means to children? Conceptually it is a bit like setting a flag, and then in another forever block, if that flag is set, looping the background functionality. 'Stop' is like clearing the flag, sort of, because it stops at the end, not when the flag is cleared.

'Background once' is like setting a flag somewhere, then in another forever block, if the flag is set, trigger the action and then clear the flag.

It's one of those 'two very different ways to do the same thing' issue, I think.  It's hidden magic really, isn't it?

**Comment by jaustin** [comment]
> 2\. Looks like the once in the block parameter is supposed to be in the foreground and there seems a bug in live if it is not blocking foreground thread. See the documentation help.

I just went back to https://makecode.microbit.org/v2#editor and I think it's still at odds with the documentation - IE async in all cases. So I'd say for compatibility we probably need be consistent with the behaviour not the docs? (see https://github.com/microsoft/pxt-microbit/issues/3823 from 2020)

**Comment by abchatra** [comment]
Ok will try to see how we can make the default as in background.
