### ISSUE TITLE
Unable to drag and drop HEX files from my windows 10 desktop to my micro:bit V2.2

### ISSUE THREAD

**Issue by indostic** [microsoft/pxt-microbit#5231]
Unable to drag and drop HEX files from my windows 10 desktop to my micro:bit V2.2

flashes eror 529 code on led matrix display

[DETAILS.TXT](https://github.com/microsoft/pxt-microbit/files/11714907/DETAILS.TXT)
[FAIL.TXT](https://github.com/microsoft/pxt-microbit/files/11714908/FAIL.TXT)

**Comment by martinwork** [comment]
To clear errors in the range 500-599, send any compatible program hex to micro:bit, such as the original out of box software.
https://microbit.org/get-started/user-guide/out-of-box-experience/

Error 529 is listed here:
https://support.microbit.org/en/support/solutions/articles/19000016969-micro-bit-error-codes
"The micro:bit has detected an incompatible image. This can occur when you If you attempt to use an old .hex file with the [latest micro:bit.](https://support.microbit.org/support/solutions/articles/19000119052-new-details-of-the-latest-micro-bit-revision) Try updating the hex file in the editor in which it was created and downloading it again."

Can you send the hex file which caused the error?

Please also see this article.
https://support.microbit.org/en/support/solutions/articles/19000145576-error-transferring-file-to-the-micro-bit-since-windows-update-in-february-2023
Until this problem is fixed, dragging program files to the MICROBIT drive, or firmware to the MAINTENANCE drive, may require several tries. Related: https://github.com/microsoft/pxt-microbit/issues/5100

If it's still not working, please create a ticket at https://support.microbit.org/.

**Comment by martinwork** [comment]
The DETAILS.TXT suggests updating the firmware has failed because of the Windows problem, and it is stuck in MAINTENANCE mode. I would simply keep trying the firmware update until the MICROBIT drive appears.
https://microbit.org/get-started/user-guide/firmware/

**Comment by abchatra** [comment]
This is a hardware issue and workaround given.
