### ISSUE TITLE
After signing out, I can sign back in without entering password

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#5264]
**Describe the bug**

Having signed in (Continue with Microsoft), and then signed out, I can sign back in without re-entering my password. Only the email address is requested.

How can I fully sign out, so a password is required?

What can the iOS micro:bit app do to ensure that signing out means the next user of an iPad can't sign in to my account?

**Expected behavior**

Sign out should fully sign out, so signing in needs a password, otherwise it is unsafe for shared devices.

**micro:bit version (please complete the following information):**

not hardware related 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows, iPadOS
 - Browser [e.g. chrome, safari] Chrome, Safari, WebKit

**Comment by abchatra** [comment]
We don't save the sign-in information unless user asks us to remember them explicitly in the following dialog. If that is not the case let us know.

![image](https://github.com/microsoft/pxt-microbit/assets/6107272/eadd4ded-25cf-4483-9b4b-d14e6130a6c8)

**Comment by abchatra** [comment]
@eanders-ms to confirm.

**Comment by eanders-ms** [comment]
This is the browser reusing cached credentials. Behavior here can be controlled to a degree via the `prompt` parameter. For Microsoft accounts it is possible to force the user to have to re-enter credentials, if that's the behavior we want. This does not seem to be possible for Google accounts, but more research needed.

MSAL prompt parameter: https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-js-prompt-behavior#supported-prompt-values
Google prompt parameter: https://developers.google.com/identity/openid-connect/openid-connect#prompt


I wonder if a better solution would be for the school district to clear browser storage when the student logs out of the shared device. This kind of policy is common for shared desktop computers, but whether it extends to iOS devices I don't know.

**Comment by eanders-ms** [comment]
Actually, we can sign out more completely using this api: https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-sign-in?tabs=javascript2#sign-out-with-a-redirect

Google has an equivalent call.

**Comment by eanders-ms** [comment]
Some exploration here reveals limited options, and they differ by provider. Here's what I found (tested on Windows and iOS):

**Microsoft Accounts**
* No option to clear credentials cached for the MakeCode app specifically. The browser's credential cache is not per-application.
* When the user signs out of MakeCode, we can sign them out of the browser session (all MSA-credentialed apps), but SSO will allow them to sign back in without a password using the platform account.
* MakeCode can require the user to re-type their MSA/AAD credentials, negating SSO entirely. This requires manual typing of full email address and password.

**Google Accounts**
* No option to clear credentials cached for the MakeCode app specifically.
* No option to sign user out of browser session.
* No option to require typed credentials.

> How can I fully sign out, so a password is required?

Due to our dependence on external identity services, we are constrained by the features they offer. Even so, attempting to resolve this issue solely at the application level doesn't effectively mitigate the problem. For instance, even if we enforce a password requirement for MakeCode, another browser application might still utilize SSO. The matter needs to be tackled at the device level: the previous user should lock the device, and the subsequent user must re-authenticate to unlock it. This approach will segment all user-specific cached credentials in the browser.

**Comment by abchatra** [comment]
I think these scenarios are covered by the identity saying don't trust this browser (or this is a public machine). Not much we can do as a product which leverages these identities and doesn't have our own identity.

**Comment by abchatra** [comment]
Can't fix

**Comment by martinwork** [comment]
@eanders-ms @abchatra Thanks for looking into it.
