### ISSUE TITLE
Neopixel problem

### ISSUE THREAD

**Issue by crouse12** [microsoft/pxt-microbit#5335]
When I import bluetooth extensions, I cannot import neopixel extensions.
May I know how to fix it?

![image](https://github.com/microsoft/pxt-microbit/assets/25700616/e21f2669-ddac-426f-b809-168f21f838fe)

**Comment by jwunderl** [comment]
Unfortunately, the neopixel package [disables bluetooth](https://github.com/microsoft/pxt-neopixel/blob/master/pxt.json#L33), which from my understanding comes down to timing issues preventing the two services from running at the same time -- so at this time I don't believe there is a way to use both at the same time. This may be something we can revisit and see if there are any other options now as this was something set 7 years ago and significant changes have been made since then (including e.g. micro:bit V2 being released) but that will require some investigation on our side.

**Comment by abchatra** [comment]
We can't fix this due to timing issue.
