### ISSUE TITLE
Switching from BLOCK to PYTHON : TRANSFERRED to micro:bit only the blocks, not the phyton!! 

### ISSUE THREAD

**Issue by 6a5h4** [microsoft/pxt-microbit#5375]
I wrote a program in blocks, switched it from BLOCKS to PHYTON, programmed more and more in PHYTON, saved it and then started the TRANSFER to the micro:bit, testing, all worked the same, then bugfixing in PHYTON, save, transfer, the same as before... and so one.
After more than 100 edits of the PHYTON code, i switched back from PHYTON to BLOCKS, and there was the old BLOCKS program, of the first time, before i switched it to PHYTON!! The editor has more than one program in his memories, so it only transfer BLOCKS to the micro:bit, never it transferred the PHYTON code to the micro:bit!

My project is halted due to this severe error until you fix that.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ EG V1.3, V1.5, V2.0, or specify it's not hardware related ]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by martinwork** [comment]
@abchatra  Please see the simple example below.

Errors in Python code are not highlighted, and mostly simply ignored. When there is an error, download, blocks mode and the simulator seem to quietly fall back to the last good Blocks (or is it Javascript?) code.

Without warning, switching to Blocks mode loses all changes in Python code since an error was introduced.

One partial workaround is to test every change to the Python code by trying to switch to Javascript mode. That at least reveals that there is an error without losing code, but doesn't give any clue to its location. 
![image](https://github.com/microsoft/pxt-microbit/assets/989126/74b14748-83a3-40e9-bf5d-f269fbbf62c9)


For a simple example, start with this code:
```
basic.show_number(0)

def on_forever():
    pass
basic.forever(on_forever)
```

Create an error. The error is not highlighted.
```
basic.show_number(0)

def on_forever():
    sleep(1000)
basic.forever(on_forever)
```

Change the number
```
basic.show_number(1)

def on_forever():
    sleep(1000)
basic.forever(on_forever)
```

Changes after the error are simply ignored by download or a switch to blocks, and the simulator 
![image](https://github.com/microsoft/pxt-microbit/assets/989126/d537b673-acd8-4424-91c1-2f2d2a1dbb32)

**Comment by riknoll** [comment]
this doesn't repro in beta
