### ISSUE TITLE
error 927

### ISSUE THREAD

**Issue by Juan-zerolo** [microsoft/pxt-microbit#5419]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ EG V1.3, V1.5, V2.0, or specify it's not hardware related ]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by martinwork** [comment]
@Juan-zerolo Please see https://support.microbit.org/support/solutions/articles/19000016969-micro-bit-error-codes which says error 927 means
> The program is incompatible with the micro:bit version you are using. You are trying to use a feature designed for micro:bit V2 on a micro:bit V1 or an extension that is only compatible with a micro:bit V1 board on a micro:bit V2.

An extension added to a project may still make the project incompatible, even if the project does not use the extension.
 
If it's not obvious what the problem is, or if there seems to be a different problem, please send your project, either as a hex file or shared project URL.
