### ISSUE TITLE
'For element value of list' block value behaviour in Beta

### ISSUE THREAD

**Issue by microbit-giles** [microsoft/pxt-microbit#5552]
**Describe the bug**
Possibly following the Blockly update, the 'for element (value) of (list)' block in the Beta release now has a drop-down for 'value' - we think this should remain as it is in the current live release, i.e. not a drop-down.

Live release (correct)
![image](https://github.com/microsoft/pxt-microbit/assets/42380137/d8547790-fea1-4f56-ab38-162c57835f5a)

Beta (we think this is incorrect):
![image](https://github.com/microsoft/pxt-microbit/assets/42380137/889df075-fe1e-4366-9510-fff2449c02db)

**To Reproduce**
1. Go to https://makecode.microbit.org/beta#editor
2. Click on Loops
3. Scroll down to 'for element (value) of (list)'

**Expected behavior**
This block should not show the option to select a different variable already created instead of using [value]. The “for element [value] of [list]” should let you select a variable in place of [list], as that is the list/array/object to iterate, but [value] is a new variable created only for the loop, to contain the array item for this iteration, so selecting a different variable already created somewhere else shouldn’t be allowed.

**Screenshots**
see above

**Comment by riknoll** [comment]
@microbit-giles the ability to change to a different variable has always been an option for this block. In the live editor, you can right click on the variable to open a dropdown and choose a new value. The change here was to remove that hidden functionality and make the behavior more discoverable by making the UI consistent with our other dropdown blocks. This change also affects the `for index from 0 to 4` block, which has the same UI.

We let you swap the variable because it's required for nested loops. If you wanted to, say, loop over every led in the micro:bit screen then you need to be able to remap those variables like so:

![image](https://github.com/microsoft/pxt-microbit/assets/13754588/a265d1d7-5b94-44d2-8c79-ca01d60f8f96)

Also, it's worth noting that the variables from both `for index` and `for of` loops have always mapped to regular variables that show up in the variables category of the toolbox. Once one of these loops is dragged into the workspace, the corresponding variable gets added to the project's variable list and won't go away even if the loop itself is deleted. This new UI brings the rendering of these blocks closer to the rendering of normal variables, which again makes everything much more consistent.

**Comment by microbit-giles** [comment]
@microbit-carlos @jaustin FYI - I think you may have some thoughts on this?
