### ISSUE TITLE
Teacher Tool: Print view broken for resized feedback

### ISSUE THREAD

**Issue by thsparks** [microsoft/pxt-microbit#5611]
![Image](https://github.com/microsoft/pxt-microbit/assets/69657545/704a1400-f463-43e6-9c5d-6aa0c3e8e7e4)

**Comment by abchatra** [comment]
@thsparks I can't reproduce this.

**Comment by thsparks** [comment]
I am still able to in beta. Exact steps are:
1. Run eval on a project with at least one criteria (I was using blocks exist)
2. After it's done running, add enough text in the feedback box that it has to expand
3. Click print

Tested on Edge

![image](https://github.com/user-attachments/assets/6f50907f-278d-49c7-b70d-a0451e96191a)

**Comment by eanders-ms** [comment]
Culprit seems to be the animation-based autoResize feature of the Textarea control. I don't think we can use this for printable content because the animation doesn't allow proper reflow in the printed layout. An alternative is to enable the textarea resize grabber and let the user expand it manually.

**Comment by thsparks** [comment]
Manual resize might work, but we'd want to ensure we can still expand it automatically when the field is populated for AI responses, etc...

Another option might be to fully swap-out the control in print view for a simpler text box.

**Comment by eanders-ms** [comment]
A different control for print that shows the full content is a great idea. It can just be a div. Will go with that.
