### ISSUE TITLE
Cannot open help documentation about 'Play a sound expression' in JavaScript and Python editor

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5666]
**Describe the bug**
Cannot open help documentation about 'Play a sound expression' in JavaScript and Python editor
 
**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Create or open **JavaScript/Python editor.**
3.Toolbox->**Music**, open the help documentation of block **'melody at tempo 120', 'tone for duration' and 'melody'.**
 
**Actual behavior:**
Cannot open the documentation, shows' Oops we could not load the documentation, please check your internet connection'.
 
**Expected behavior:**
Open the help documentation correctly.
 
**Screen Recording:**
![playsound](https://github.com/microsoft/pxt-microbit/assets/148834117/270e4821-2d43-4e34-806e-79c538d6a7b2)

**Additional context:**
1.OS: Windows11, iMac Ventura 13.6.6
2.makecode.microbit,org version: 7.0.9
3.Microsoft MakeCode version: 10.0.21

**Comment by ganicke** [comment]
@abchatra - part of the problem here is that half of the music docs are sourced in the `mixer` lib. The `help=` path for both `music` lib and `mixer` lib is set to use `./reference/music`. It seems that lookup hierarchy is not linking in `./pxt-common-packages/libs/mixer` when looking for a doc when it's help path is `help=music/xxyyzz`.

**Comment by riknoll** [comment]
@ganicke for historical reasons we don't actually include the mixer lib in pxt-microbit at all; long ago we redefined the melody format for pxt-microbit in pxt-common-packages and the two music implementations have been incompatible ever since.

I guess the fix here is to just copy the mixer docs into pxt-microbit. The melody and sound effect blocks will probably also require slightly different documentation since those are the two major points of differentiation between the two.

**Comment by ganicke** [comment]
@riknoll - yes, that's right. Had I investigated more under `./libs` I would've noticed. Thanks, I'll get some micro:bit versions or those pages in there.

**Comment by fionama100** [comment]
I have verified this bug in the latest build makecode microbit.org version: 7.0.16, and the help documentation of block 'melody at tempo 120' and 'tone for duration' can be open successfully. But the help documentation of block **melody** still Cannot be opened, shows: "Oops we could not load the documentation, please check your internet connection", so I reopen this bug.

**Comment by srietkerk** [comment]
This is fixed via https://github.com/microsoft/pxt-microbit/pull/5880.

**Comment by Ramanan0530** [comment]
I verified this bug in the latest version: 7.0.36 and it has been fixed.
