### ISSUE TITLE
"Rock Paper Scissors Teams": Pops error while converting Block/JavaScript code to Python

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5703]
**Describe the bug**
"Rock Paper Scissors Teams": Pops error while converting Block/JavaScript code to Python
 
**Steps to reproduce the behavior**
 1.Navigate to  https://makecode.microbit.org/beta
 2.**Radio Games->Rock Paper Scissors Teams**->Show Instructions.
 3.Hover mouse to final code and click Edit
 4. **Switch editor** from **Block/JavaScript to Python** and observe

**Actual behavior**
Pops 1 error "Unhandled exception : Value Error" while switch editor from Block/JavaScript to Python
 
**Expect behavior**
Successfully switch to Python Editor without Error.

**Screen Recording:**
![popserror](https://github.com/microsoft/pxt-microbit/assets/148834117/2e64fd8c-0824-4bb9-8e26-9f81c45e5026)

**Additional context**
1.OS: Windows 11 Enterprise
2.Browser: Edge
3.makecode.microbit,org version: 7.0.12
4.Microsoft MakeCode version: 10.0.23

**Comment by riknoll** [comment]
the issue here is that we emit python's `index` function when converting the `Array.indexOf` function to python. `index` is definitely the closest pythonic equivalent, but it has different semantics (it throws an exception when something is missing from an array instead of returning -1).

i guess the fix here is to emit some non-standard python when we convert. i'd rather the `list.index()` function keep having the correct semantics instead of making it match the js semantics

**Comment by fionama100** [comment]
I verified this bug in the latest version: 7.0.25 and it has been fixed.
