### ISSUE TITLE
The blocks found by search cannot be added to the project on iPad/Android

### ISSUE THREAD

**Issue by microbit-caroline** [microsoft/pxt-microbit#5962]
**Describe the bug**
This issue was raised in a support ticket https://support.microbit.org/a/tickets/82600 (private)
The blocks found by search cannot be added to the project running on an iPad or Android device. 

**To Reproduce**
1. Create a new project or open an existing project in MakeCode using the Chrome/Safari browser or by clicking 'create code' in iOS app.
2. Using the default blocks view, click the search bar.
3. Type 'button' (can be any block name), in the search -a window will display all the blocks found
4. Attempting to drag any of the blocks results in the block being highlighted but it is not able to be moved into the project workspace.
5. Dismiss the search results and try to drag any block from the toolbox into the project workspace, again the block is highlighted but cannot be moved into the workspace.
6. Only refreshing the browser window or clicking the back arrow (iOS app) to return to the app menu and then selecting 'create code' again corrects the problem.

See short video:
https://github.com/user-attachments/assets/882beb72-a3bd-4d27-bea3-257ddf9f961d

**Expected behavior**
The same behaviour as previous versions of MakeCode.

**micro:bit version (please complete the following information):**
N/A 

**Desktop**
 - OS: works on Windows/MacOS
 - Works on Chrome/Edge on Windows
 - Works on Chrome/Safari on MacOS
 - Works on all versions of MakeCode on Windows/MacOS

**iPasOS/Android **
 - Does not work on iPadOS 17.x/18.x 
 - Does not work on Android 14
 - Does not work on Chrome or Safari on iPadOS or Chrome on Android
 - Works on version 6.x  of MakeCode https://makecode.microbit.org/v6 on iPad/Android

**Additional context**
Using the search in JavaScript or Python view works as expected.

**Comment by martinwork** [comment]
Freezing has also been reported in support ticket https://support.microbit.org/helpdesk/tickets/82682 (private)

**Comment by riknoll** [comment]
@martinwork is it also on ios? if so, it might just be the same issue and be fixed with the PR I just merged.

blockly has a tendency to break whenever it encounters an exception that happens in the gesture chain (e.g. something in an on click handler). once it breaks, it's broken until you refresh the page. that's why sometimes you can trigger an exception and the whole blockly workspace stops working. in this case, clicking on the search input triggers the exception

i really need to set up some time with the blockly team to chat about how to harden this code path up a bit. would be great if it could try and recover a little more gracefully by just cancelling the current gesture.

**Comment by riknoll** [comment]
chrome on ios is secretly just safari, but i'm guessing android is the same issue. i don't have an android device handy for testing but i'm willing to bet it's really more of a touch issue than anything related to those browsers.
