### ISSUE TITLE
multiple call to control.inBackground cause variable pollution

### ISSUE THREAD

**Issue by lrscp** [microsoft/pxt-microbit#6025]
**Describe the bug**
multiple call to control.inBackground make the program run weird 

**To Reproduce**
1. burn the following javascript code to microbit v2
===>
  let test1 = 100
  let test2 = 0
  
  control.inBackground(function() {
      while (true) {
          serial.writeLine("test1 " + test1)
          pause(1000)
          test1 += 1
      }
  })
  
  control.inBackground(function() {
      while (true) {
          serial.writeLine("test2 " + test2)
          pause(1000)
          test2 += 2
      }
  })
 <===
2. observe the serial com output，result shows as follow
===>
test1 100                     
test2 2                       
test1 102                     
test2 6                       
test1 104                     
test2 10                      
test1 106                     
test2 14                      
test1 108                     
test2 18                      
test1 110
<===
seams like test1 conflit with test2 in memory

**Expected behavior**
===>
test1 100                     
test2 0                       
test1 101                     
test2 2                       
test1 102                     
test2 4                      
test1 103                     
test2 6                     
test1 104                     
test2 8                     
test1 105
<===

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ V2 ]

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - MakeCode Offline Version [7.0.49]

**Comment by martinwork** [comment]
@lrscp The weirdness is in the serial output, not the variables.

A serial write call fails when serial is already in use by another fiber. 

In the example, I think every other write from test1/test2 fails, because control has passed from test2/test1 while its serial write call is waiting for space in the serial buffer. 

Increasing the serial buffer size fixes things. It could still drop output if writes happen fast enough to fill the buffer 
https://makecode.microbit.org/_CEH8mpcJib07

Or keep all serial output in one place. 
https://makecode.microbit.org/_C9dLwURLwAe3

Related:
https://github.com/lancaster-university/codal-microbit-v2/issues/398
https://github.com/microsoft/pxt-microbit/issues/5417

**Comment by tballmsft** [comment]
Thanks @martinwork
