### ISSUE TITLE
Downloading file into a dropbox folder makes it impossible to upload to a microbit

### ISSUE THREAD

**Issue by nielsswinkels** [Microsoft/pxt-microbit#672]
Ran into this strange bug today. If you download the hexfile and save it into a dropbox folder on the (windows) computer, it will complain when you try to then copy it to the microbit. (It does not depending on whether the file is being synced to dorpbox or if syncing is done.)

The error message (translated): "1 interrupted process. Do you want to copy this file without properties? The file microbit-simpleDice has properties that can't be copied to the new location. [yes / skip / cancel ]"

**Comment by abchatra** [comment]
Can you copy the file into a desktop and then try uploading to microbit?

**Comment by nielsswinkels** [comment]
Interesting question. Didn't test that with the person that had the bug. I don't have any dropbox so I can't test it.

**Comment by zxtwonder** [comment]
When selecting "yes", can the file be successfully copied and micro:bit be flashed?

From the message "copy this file without properties", it is probably related to NTFS Alternate Data Stream, which is used by Dropbox client. Since DAPLink exposes micro:bit with FAT file system, which does not support ADS, Windows warns that properties added by Dropbox cannot be copied. It should be perfectly safe to choose "yes" in this case.

**Comment by nielsswinkels** [comment]
It was a while ago, but I'm sure we tried that and it didn't work.

**Comment by abchatra** [comment]
No further report of this issue. Closing. Please reopen if you see this again.
