### ISSUE TITLE
Green Screen mode issue

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#858]
**Repro steps:**
• Navigate to https://makecode.microbit.org/alpha
• Click "Blinky" to open this example
• Click "More..." -> "Green Screen On" to open Green Screen mode
• Click "{ }JavaScript" to switch to javaScript editor
 
**Expected result:**
The code color should be same on different browsers
![issue2](https://user-images.githubusercontent.com/23466737/40965599-abc97822-689d-11e8-9ffe-7cdfff4b08c8.PNG)

**Actual result:**
The code color should be same on different browsers
![issue2issue](https://user-images.githubusercontent.com/23466737/40965603-b236d2cc-689d-11e8-81dc-e1e0afa8e2b2.PNG)

**Comment by abchatra** [comment]
We removed green screen mode for now.

**Comment by microbit-mark** [comment]
Hey @abchatra are you able to fix the issue and re-enable green screen? It would be a useful mode

**Comment by CleoQc** [comment]
Yes please!

**Comment by riknoll** [comment]
For context, the original issue here might be because one of the browsers looks like it has high contrast mode enabled and the other doesn't. 

As for the green screen mode, consensus on our team was that it was too narrow a feature to give it such prime real estate and it adds a maintenance burden (we already have two themes for each of our editors). Still feel free to open an issue to track adding it! I'm going to close this one because it was originally about something else.
